/** القاموس العربي — مفاتيح مشتركة ثم مفاتيح كل صفحة. */
export const AR: Record<string, string> = {
  // ---------- عام ----------
  'app.name': 'CleanShelf',
  'app.by': 'من تطوير Alcode',
  'app.byShort': 'من تطوير {company}',

  'common.cancel': 'إلغاء',
  'common.confirm': 'تأكيد',
  'common.save': 'حفظ',
  'common.saving': 'جارٍ الحفظ…',
  'common.delete': 'حذف',
  'common.remove': 'إزالة',
  'common.close': 'إغلاق',
  'common.apply': 'تطبيق',
  'common.open': 'فتح',
  'common.refresh': 'تحديث',
  'common.rescan': 'إعادة الفحص',
  'common.scan': 'فحص',
  'common.scanning': 'جارٍ الفحص…',
  'common.stopScan': 'إيقاف الفحص',
  'common.loading': 'جارٍ التحميل…',
  'common.search': 'بحث',
  'common.searchQuick': 'بحث سريع…',
  'common.selectAll': 'تحديد الكل',
  'common.clearAll': 'إلغاء التحديد',
  'common.selected': 'محدَّد',
  'common.viewAll': 'عرض الكل',
  'common.viewDetails': 'عرض التفاصيل',
  'common.details': 'تفاصيل',
  'common.name': 'الاسم',
  'common.size': 'الحجم',
  'common.date': 'التاريخ',
  'common.path': 'المسار',
  'common.status': 'الحالة',
  'common.type': 'النوع',
  'common.free': 'متاحة',
  'common.used': 'مستخدمة',
  'common.total': 'الإجمالي',
  'common.item': 'عنصر',
  'common.items': 'عنصر',
  'common.file': 'ملف',
  'common.files': 'ملف',
  'common.day': 'يوم',
  'common.days': 'يوم',
  'common.hours': 'ساعة',
  'common.category': 'فئة',
  'common.categories': 'فئة',
  'common.nothing': 'لا شيء',
  'common.empty': 'لا شيء هنا',
  'common.failed': 'تعذّر إتمام العملية',
  'common.settings': 'الإعدادات',
  'common.back': 'رجوع',
  'common.retry': 'إعادة المحاولة',
  'common.copy': 'نسخ',
  'common.copied': 'تم النسخ',

  'unit.b': 'بايت',
  'unit.kb': 'كيلوبايت',
  'unit.mb': 'ميغابايت',
  'unit.gb': 'غيغابايت',
  'unit.tb': 'تيرابايت',

  // ---------- الشريط الجانبي والعناوين ----------
  'nav.disk': 'أدوات القرص',
  'nav.privacy': 'الخصوصية والأمان',
  'nav.system': 'النظام',
  'nav.pin': 'تثبيت في الرئيسية',
  'nav.unpin': 'إلغاء التثبيت',

  'page.dashboard': 'الرئيسية',
  'page.dashboard.sub': 'نظرة عامة على صحة جهازك وتنظيف بضغطة واحدة',
  'page.overview': 'نظرة عامة',
  'page.overview.sub': 'توقّع امتلاء القرص وأكبر فرص التنظيف',
  'page.plan': 'خطة الصيانة',
  'page.plan.sub': 'مهام دورية تحافظ على جهازك نظيفًا',
  'page.cleaner': 'منظّف القرص',
  'page.cleaner.sub': 'حرّر المساحة بحذف الملفات غير الضرورية',
  'page.uninstaller': 'إزالة البرامج',
  'page.uninstaller.sub': 'أزل البرامج المثبَّتة مع مخلّفاتها',
  'page.files': 'مدير الملفات',
  'page.files.sub': 'تصفّح وأعد تسمية ونظّم ملفاتك',
  'page.tags': 'محرر وسوم الأغاني',
  'page.tags.sub': 'حرّر معلومات وأغلفة ملفات MP3 كما في Mp3tag',
  'page.duplicates': 'الملفات المكرّرة',
  'page.duplicates.sub': 'اعثر على النسخ المكرّرة واسترجع المساحة',
  'page.largefiles': 'أكبر الملفات',
  'page.largefiles.sub': 'حدّد أكبر الملفات المستهلكة للمساحة',
  'page.startup': 'برامج بدء التشغيل',
  'page.startup.sub': 'تحكّم بما يعمل تلقائيًا عند إقلاع الجهاز',
  'page.system': 'معلومات النظام',
  'page.system.sub': 'حالة المعالج والذاكرة والأقراص',
  'page.processes': 'العمليات',
  'page.processes.sub': 'ما يعمل الآن على جهازك، وإنهاء ما تريد',
  'page.services': 'خدمات النظام',
  'page.services.sub': 'تشغيل وإيقاف خدمات النظام وlaunchd',
  'page.network': 'الشبكة',
  'page.network.sub': 'المحوّلات والاتصالات النشطة وأدوات التشخيص',
  'page.diskanalyzer': 'محلّل المساحة',
  'page.diskanalyzer.sub': 'اعرف أين تذهب مساحة قرصك بالضبط',
  'page.extras': 'مجلدات واختصارات',
  'page.extras.sub': 'المجلدات الفارغة والاختصارات المعطوبة',
  'page.history': 'سجل التنظيف',
  'page.history.sub': 'ما نُظّف سابقًا وكم مساحة تحرّرت',
  'page.mactools': 'أدوات ماك',
  'page.mactools.sub': 'مخلّفات التطبيقات المحذوفة وملفات اللغات',
  'page.privacy': 'خصوصية المتصفح',
  'page.privacy.sub': 'امسح سجل التصفح والكوكيز والجلسات من كل المتصفحات',
  'page.shredder': 'الممزّق الآمن',
  'page.shredder.sub': 'احذف الملفات الحساسة بحيث يستحيل استرجاعها',
  'page.downloads': 'التنزيلات القديمة',
  'page.downloads.sub': 'ما نسيته في مجلد التنزيلات منذ شهور',
  'page.report': 'تقرير النظام',
  'page.report.sub': 'لقطة كاملة عن جهازك قابلة للحفظ والمشاركة',
  'page.settings': 'الإعدادات',
  'page.settings.sub': 'المظهر واللغة والسلوك وخيارات الأدوات',

  // ---------- لوحة الأوامر ----------
  'palette.pages': 'الصفحات',
  'palette.actions': 'إجراءات',
  'palette.placeholder': 'اكتب اسم صفحة أو إجراء…',
  'palette.noResults': 'لا نتائج',
  'palette.smartClean': 'تنظيف ذكي الآن',
  'palette.theme': 'تبديل المظهر (الحالي: {mode})',
  'palette.lang': 'تبديل اللغة (الحالية: {lang})',
  'palette.report': 'إنشاء تقرير عن الجهاز',
  'palette.ask': 'اسأل المساعد الذكي',
  'palette.aiOn': 'تفعيل مميزات الذكاء الاصطناعي',
  'palette.aiOff': 'تعطيل مميزات الذكاء الاصطناعي',
  'palette.hintOpen': 'للفتح',
  'palette.hintMove': 'للتنقّل',

  // ---------- المظهر ----------
  'theme.system': 'حسب النظام',
  'theme.light': 'فاتح',
  'theme.dark': 'داكن',
  'theme.tip': 'المظهر: {mode} — اضغط للتبديل',

  // ---------- الرئيسية ----------
  'dash.period.week': 'هذا الأسبوع',
  'dash.period.month': 'هذا الشهر',
  'dash.period.year': 'هذه السنة',
  'dash.mainDisk': 'القرص الرئيسي',
  'dash.planTile': 'خطة الصيانة',
  'dash.diskTile': 'حالة القرص',
  'dash.overdue': 'متأخرة',
  'dash.due': 'مستحقة',
  'dash.inPlan': 'في الخطة',
  'dash.done': 'منجزة',
  'dash.seg.used': 'مستخدمة',
  'dash.seg.junk': 'قابلة للتنظيف',
  'dash.seg.free': 'متاحة',
  'dash.totalOf': '{unit} الإجمالي',
  'dash.outOf100': 'من 100',
  'dash.smartClean': 'تنظيف ذكي بضغطة واحدة',
  'dash.cleaning': 'جارٍ التنظيف الذكي…',
  'dash.scanDevice': 'فحص الجهاز',
  'dash.factors': 'عوامل الصحة',
  'dash.pinnedTools': 'أدواتك المثبَّتة',
  'dash.quickTools': 'أدوات سريعة',
  'dash.allTools': 'كل الأدوات',
  'dash.lastCleans': 'آخر عمليات التنظيف',
  'dash.cpu': 'المعالج',
  'dash.memUsed': 'الذاكرة المستخدمة',
  'dash.diskFree': 'المساحة المتاحة',
  'dash.uptime': 'مدة التشغيل',
  'dash.outOfTotal': 'من أصل {size}',
  'dash.ofTotal': 'من {size}',
  'dash.hoursShort': '{n} ساعة',

  'health.evaluating': 'جارٍ تقييم جهازك…',
  'health.excellent': 'جهازك بحالة ممتازة',
  'health.good': 'جهازك بحالة جيدة',
  'health.fair': 'جهازك يحتاج بعض العناية',
  'health.poor': 'جهازك يحتاج تنظيفًا الآن',
  'health.canFree': 'يمكن تحرير نحو {size} بضغطة واحدة دون أي مخاطرة.',
  'health.clean': 'لا توجد ملفات غير ضرورية تستحق التنظيف الآن.',
  'health.scanningDesc': 'نفحص الملفات المؤقتة والذاكرة والقرص وبرامج بدء التشغيل…',
  'health.idleDesc': 'اضغط "فحص الجهاز" لتقييم حالته الحالية.',
  'health.failed': 'تعذّر تقييم الجهاز: {msg}',
  'dash.cleanNothing': 'لا شيء يحتاج تنظيفًا — جهازك نظيف',
  'dash.cleanDone': 'تم تحرير {size} من {n} فئة',
  'dash.cleanFailed': 'فشل التنظيف الذكي: {msg}',

  // ---------- نظرة عامة ----------
  'ov.measuring': 'نقيس مساحة قرصك…',
  'ov.almostFull': 'قرصك على وشك الامتلاء',
  'ov.shrinking': 'مساحة قرصك تتناقص',
  'ov.healthy': 'مساحة قرصك بحالة جيدة',
  'ov.freeSpace': 'المساحة المتاحة',
  'ov.perDay': 'يُستهلك يوميًا',
  'ov.perDayDesc': 'متوسط ما تستهلكه مساحتك كل يوم',
  'ov.needDays': 'نحتاج بضعة أيام من القياسات',
  'ov.forecast': 'توقّع امتلاء القرص',
  'ov.forecastDesc': 'يُحسب من قياسات الأيام السابقة',
  'ov.forecastIn': 'بهذا المعدّل يمتلئ القرص بعد نحو {n} يومًا',
  'ov.biggest': 'أكبر فرصة تنظيف',
  'ov.highImpact': 'أثر كبير',
  'ov.others': 'فرص أخرى',
  'ov.planTasks': 'مهام الخطة',
  'ov.allDone': 'كل مهام الخطة منجزة — جهازك في أفضل حال',
  'ov.junkDetail': '{size} من الملفات المؤقتة والذواكر',
  'ov.dupDetail': 'نسخ متطابقة تهدر المساحة بلا فائدة',
  'ov.largeDetail': 'أكبر الملفات المستهلكة للمساحة',
  'ov.dlDetail': 'ما نسيته في مجلد التنزيلات منذ شهور',

  // ---------- خطة الصيانة ----------
  'plan.never': 'لم تُنفَّذ بعد',
  'plan.today': 'نُفِّذت اليوم',
  'plan.daysAgo': 'آخر مرة قبل {n} يوم',
  'plan.every': 'كل {n} يوم',
  'plan.markDone': 'تسجيلها كمنجزة',
  'plan.marked': 'سُجّلت "{label}" كمنجزة',
  'plan.badge.overdue': 'متأخرة',
  'plan.badge.due': 'مستحقة',
  'plan.badge.done': 'منجزة',
  'plan.task.junk': 'تنظيف الملفات غير الضرورية',
  'plan.task.privacy': 'مسح بيانات التصفح',
  'plan.task.downloads': 'ترتيب مجلد التنزيلات',
  'plan.task.duplicates': 'إزالة الملفات المكرّرة',
  'plan.task.largefiles': 'مراجعة أكبر الملفات',
  'plan.task.startup': 'مراجعة برامج بدء التشغيل',
  'plan.task.uninstaller': 'إزالة البرامج غير المستخدمة',
  'plan.task.extras': 'حذف المجلدات الفارغة والاختصارات المعطوبة',

  // ---------- الإعدادات ----------
  'set.language': 'اللغة',
  'set.language.sub': 'يتغيّر اتجاه الواجهة تلقائيًا',
  'set.arabic': 'العربية',
  'set.english': 'English',
  'set.appearance': 'المظهر',
  'set.theme': 'السمة',
  'set.accent': 'لون التمييز',
  'set.accent.sub': 'الأزرار والعناصر النشطة',
  'set.behavior': 'السلوك',
  'set.tray': 'التصغير إلى شريط النظام',
  'set.tray.sub': 'يبقى التطبيق عاملًا عند إغلاق النافذة',
  'set.launch': 'التشغيل عند بدء النظام',
  'set.launch.sub': 'يفتح التطبيق تلقائيًا بعد تسجيل الدخول',
  'set.notif': 'إشعار عند اكتمال التنظيف',
  'set.notif.sub': 'يظهر ما تحرّر من مساحة',
  'set.autoscan': 'فحص تلقائي عند الفتح',
  'set.autoscan.sub': 'يحسب درجة الصحة فور فتح التطبيق',
  'set.tools': 'الأدوات',
  'set.dlAge': 'عمر التنزيل القديم',
  'set.shredPasses': 'مرات الكتابة في الممزّق',
  'set.once': 'مرة',
  'set.times': '{n} مرات',
  'set.daysN': '{n} يوم',
  'set.about': 'حول التطبيق',
  'set.saveFailed': 'تعذّر حفظ الإعداد: {msg}',
  'set.shortcuts': 'اختصارات لوحة المفاتيح',
  'set.sc.palette': 'لوحة الأوامر',
  'set.sc.settings': 'الإعدادات',
  'set.sc.theme': 'تبديل المظهر',

  // ---------- مكوّنات مشتركة ----------
  'palette.empty': 'لا نتائج لـ "{q}"',
  'palette.kMove': 'تنقّل',
  'palette.kOpen': 'فتح',
  'palette.kClose': 'إغلاق',
  'batch.title': 'إعادة تسمية دفعية ({n} ملف)',
  'batch.hint': 'استخدم %name% للاسم الأصلي، %n% للترقيم التسلسلي، %ext% للامتداد',
  'batch.start': 'رقم البداية',
  'batch.applying': 'جارٍ التنفيذ…',
  'batch.done': 'تمت إعادة تسمية {n} ملف',
  'batch.partial': 'تمت إعادة تسمية {n} ملف، وتعذّر {fail} ({msg})',
  'batch.failed': 'فشل بعض العمليات: {msg}',
  'scan.hashing': 'مقارنة محتوى الملفات… {i} من {n}',
  'scan.walking': 'جارٍ فحص المجلدات… {n} ملف',

  // ---------- الإعدادات (تفصيل) ----------
  'set.appearance.sub': 'اختر ما يريح عينك — يُحفظ تلقائيًا',
  'set.theme.sub': '"حسب النظام" تتبع إعداد {os} تلقائيًا',
  'set.accent.sub2': 'يغيّر لون البطاقات والأزرار في كل التطبيق',
  'set.behavior.sub': 'كيف يتصرف التطبيق في الخلفية',
  'set.tray.sub2': 'إغلاق النافذة يخفيها بدل إنهاء التطبيق، ويبقى التنظيف الذكي متاحًا من الأيقونة',
  'set.launch.sub2': 'يبدأ CleanShelf مخفيًا مع النظام (يعمل في النسخة المثبَّتة فقط)',
  'set.notif.sub2': 'تنبيه عند اكتمال التنظيف بما تحرّر من مساحة',
  'set.autoscan.sub2': 'يحسب درجة الصحة تلقائيًا — أوقفه إن كان الفحص بطيئًا على جهازك',
  'set.tools.sub': 'إعدادات افتراضية للأدوات',
  'set.dlAge.sub': 'الملفات الأقدم من هذا العدد من الأيام تُعرض في أداة التنزيلات القديمة',
  'set.shred.sub': 'أكثر = أبطأ وأصعب استرجاعًا؛ 3 مرات كافية لمعظم الاستخدامات',
  'set.shred.1': 'مرة واحدة (سريع)',
  'set.shred.3': '3 مرات (موصى به)',
  'set.shred.7': '7 مرات (أقصى حماية)',
  'set.forWinMac': 'لويندوز وماك',
  'set.checkUpdate': 'التحقق من وجود إصدار أحدث',
  'os.windows': 'ويندوز',
  'os.mac': 'ماك',

  // ---------- فئات المنظّف ----------
  'cleaner.userTemp.t': 'الملفات المؤقتة للمستخدم',
  'cleaner.userTemp.d': 'ملفات مؤقتة تتركها البرامج أثناء عملها',
  'cleaner.windowsTemp.t': 'ملفات ويندوز المؤقتة',
  'cleaner.windowsTemp.d': 'مجلد Temp الخاص بنظام ويندوز',
  'cleaner.prefetch.t': 'ذاكرة التسريع Prefetch',
  'cleaner.prefetch.d': 'يعيد ويندوز بناءها تلقائيًا، آمن غالبًا لكن قد يبطئ أول إقلاع لبرنامج',
  'cleaner.windowsUpdate.t': 'ملفات تنزيل تحديثات ويندوز',
  'cleaner.windowsUpdate.d': 'نسخ محدّثات تم تثبيتها بالفعل',
  'cleaner.thumbnails.t': 'ذاكرة الصور المصغّرة',
  'cleaner.thumbnails.d': 'يعيد ويندوز إنشاءها عند الحاجة',
  'cleaner.errorReports.t': 'تقارير أعطال ويندوز',
  'cleaner.errorReports.d': 'ملفات تشخيص أعطال قديمة',
  'cleaner.recentList.t': 'قائمة الملفات الأخيرة',
  'cleaner.recentList.d': 'اختصارات لآخر الملفات المفتوحة',
  'cleaner.chromeCache.t': 'ذاكرة تخزين Chrome المؤقتة',
  'cleaner.chromeCache.d': 'يُعاد بناؤها تلقائيًا عند تصفح المواقع',
  'cleaner.edgeCache.t': 'ذاكرة تخزين Edge المؤقتة',
  'cleaner.edgeCache.d': 'يُعاد بناؤها تلقائيًا عند تصفح المواقع',
  'cleaner.firefoxCache.t': 'ذاكرة تخزين Firefox المؤقتة',
  'cleaner.firefoxCache.d': 'يُعاد بناؤها تلقائيًا عند تصفح المواقع',
  'cleaner.deliveryOptimization.t': 'ملفات تحسين التسليم',
  'cleaner.deliveryOptimization.d': 'أجزاء تحديثات مشتركة بين الأجهزة على الشبكة',
  'cleaner.minidumps.t': 'ملفات تفريغ الذاكرة (Minidump)',
  'cleaner.minidumps.d': 'ملفات تشخيص أعطال النظام',
  'cleaner.recycleBin.t': 'سلة المحذوفات',
  'cleaner.recycleBin.d': 'إفراغ سلة المحذوفات نهائيًا — غير قابل للتراجع',
  'cleaner.mac.userCaches.t': 'ذاكرة التخزين المؤقتة للمستخدم',
  'cleaner.mac.userCaches.d': '~/Library/Caches — تُعاد بناؤها تلقائيًا',
  'cleaner.mac.systemCaches.t': 'ذاكرة التخزين المؤقتة للنظام',
  'cleaner.mac.systemCaches.d': '/Library/Caches — تحتاج صلاحيات مرتفعة',
  'cleaner.mac.userLogs.t': 'سجلات التطبيقات',
  'cleaner.mac.userLogs.d': '~/Library/Logs',
  'cleaner.mac.trash.t': 'سلة المهملات',
  'cleaner.mac.trash.d': 'إفراغ المهملات نهائيًا — غير قابل للتراجع',
  'cleaner.mac.xcodeDerived.t': 'بيانات Xcode المشتقّة',
  'cleaner.mac.xcodeDerived.d': 'DerivedData — تُعاد بناؤها عند فتح المشروع، غالبًا عدة غيغابايت',
  'cleaner.mac.xcodeDeviceSupport.t': 'ملفات دعم أجهزة Xcode',
  'cleaner.mac.xcodeDeviceSupport.d': 'نسخ رموز لإصدارات iOS قديمة — تُنزَّل ثانيةً عند الحاجة',
  'cleaner.mac.xcodeArchives.t': 'أرشيفات Xcode',
  'cleaner.mac.xcodeArchives.d': 'نسخ التطبيقات المؤرشفة للنشر — احذفها إن لم تعد تحتاجها',
  'cleaner.mac.homebrew.t': 'ذاكرة Homebrew',
  'cleaner.mac.homebrew.d': 'حزم منزَّلة سابقًا',
  'cleaner.mac.packageManagers.t': 'ذواكر مديري الحزم',
  'cleaner.mac.packageManagers.d': 'npm و Yarn و pnpm و pip و Gradle و CocoaPods',
  'cleaner.mac.safariCache.t': 'ذاكرة Safari',
  'cleaner.mac.safariCache.d': 'يُعاد بناؤها عند التصفح',
  'cleaner.mac.mailDownloads.t': 'مرفقات البريد المؤقتة',
  'cleaner.mac.mailDownloads.d': 'مرفقات فُتحت من تطبيق Mail',
  'cleaner.mac.iosBackups.t': 'نسخ احتياطية للآيفون/آيباد',
  'cleaner.mac.iosBackups.d': 'قد تكون عشرات الغيغابايت — تأكد أن لديك نسخة أخرى قبل الحذف',
  'cleaner.mac.crashReports.t': 'تقارير الأعطال',
  'cleaner.mac.crashReports.d': 'ملفات تشخيص أعطال التطبيقات',
  'cleaner.mac.quicklook.t': 'ذاكرة المعاينة السريعة',
  'cleaner.mac.quicklook.d': 'صور مصغّرة يعيد النظام بناءها',
  'cleaner.mac.savedState.t': 'حالات التطبيقات المحفوظة',
  'cleaner.mac.savedState.d': 'تُفقد نوافذ التطبيقات المفتوحة سابقًا عند إعادة التشغيل',

  // ---------- منظّف القرص ----------
  'cl.scanFailed': 'فشل الفحص: {msg}',
  'cl.restorePoint': 'جارٍ إنشاء نقطة استعادة… قد يستغرق دقيقة',
  'cl.restoreFailed': 'تعذّر إنشاء نقطة الاستعادة: {msg}',
  'cl.freed': 'تم تحرير {size} من المساحة',
  'cl.cleanError': 'حدث خطأ أثناء التنظيف: {msg}',
  'cl.summary': '{n} فئة، الإجمالي القابل للتنظيف {size}',
  'cl.selectedLabel': 'محدَّد:',
  'cl.cleanSelected': 'تنظيف المحدَّد',
  'cl.smartReview': 'مراجعة ذكية',
  'cl.smartReviewQ': 'راجع نتيجة الفحص التالية واقترح ما يُحذف أولًا وما يُترك، بإيجاز:',
  'cl.cleaning': 'جارٍ التنظيف…',
  'cl.adminTitle': 'بعض الفئات تحتاج صلاحيات مرتفعة',
  'cl.adminBody': 'الفئات التالية داخل مجلدات يملكها النظام، ولن يُحذف منها شيء بالصلاحيات الحالية:',
  'cl.adminMac': ' على ماك لا توجد "إعادة تشغيل كمسؤول"؛ نظّفها من الطرفية أو تخطَّ هذه الفئات.',
  'cl.relaunchAdmin': 'إعادة تشغيل التطبيق كمسؤول',
  'cl.thCategory': 'الفئة',
  'cl.thFiles': 'عدد الملفات',
  'cl.caution': 'انتبه',
  'cl.adminBadge': 'مدير',
  'cl.adminBadgeTip': 'يحتاج تشغيل التطبيق كمسؤول',
  'cl.failed': 'فشل',
  'cl.freedBadge': 'تم تحرير {size}',
  'cl.working': 'جارٍ…',
  'cl.error': 'خطأ',
  'cl.ready': 'جاهز',
  'cl.confirmTitle': 'تأكيد التنظيف',
  'cl.confirmBody': 'سيتم حذف {size} من {n} فئة بشكل نهائي (باستثناء سلة المحذوفات التي تُفرَّغ نهائيًا أيضًا).',
  'cl.confirmCaution': 'اخترت فئات مُعلَّمة "انتبه" — تأكد من فهم تأثيرها قبل المتابعة.',
  'cl.makeRestore': 'أنشئ نقطة استعادة نظام أولًا (تحتاج صلاحيات مدير، وقد تستغرق دقيقة)',

  // ---------- صفحات: السجل والمكرّرة والأكبر والنظام ----------
  'hi.clearConfirm': 'مسح سجل التنظيف بالكامل؟',
  'hi.cleared': 'مُسح السجل',
  'hi.totalFreed': 'إجمالي ما حُرِّر',
  'hi.ops': 'عدد عمليات التنظيف',
  'hi.lastClean': 'آخر تنظيف',
  'hi.sub': 'سجل عمليات التنظيف السابقة',
  'hi.clear': 'مسح السجل',
  'hi.none': 'لم تُنفَّذ أي عملية تنظيف بعد',
  'hi.thFreed': 'المساحة المحرَّرة',
  'hi.thCats': 'الفئات',
  'du.none': 'لم يُعثر على ملفات مكرّرة',
  'du.stopped': 'أُوقف الفحص',
  'du.failed': 'فشل البحث: {msg}',
  'du.trashConfirm': 'نقل {n} ملف إلى سلة المحذوفات؟',
  'du.trashDetail': 'سيتم الإبقاء على نسخة واحدة من كل مجموعة تكرار على الأقل إن لم تختر غير ذلك.',
  'du.deleted': 'تم حذف {n} ملف',
  'du.pick': 'اختر مجلدًا وابحث عن التكرارات',
  'du.wasted': 'هدر تقديري: {size}',
  'du.selectExtra': 'تحديد الكل عدا الأولى بكل مجموعة',
  'du.deleteSel': 'حذف المحدَّد ({n})',
  'du.empty': 'اختر مجلدًا لبدء البحث عن الملفات المكرّرة',
  'du.copies': '{n} نسخ × {size}',
  'lf.pick': 'اختر مجلدًا',
  'lf.biggerThan': 'أكبر من {size}',
  'lf.empty': 'اختر مجلدًا لعرض أكبر الملفات فيه',
  'lf.thFile': 'الملف',
  'lf.reveal': 'إظهار',
  'lf.trashConfirm': 'نقل {n} ملف إلى سلة المحذوفات؟',
  'si.failed': 'تعذّر جلب معلومات النظام: {msg}',
  'si.system': 'النظام',
  'si.host': 'الجهاز',
  'si.os': 'نظام التشغيل',
  'si.version': 'الإصدار',
  'si.cpuMem': 'المعالج والذاكرة',
  'si.usage': 'نسبة الاستخدام',
  'si.totalMem': 'إجمالي الذاكرة',
  'si.disks': 'الأقراص',
  'si.thDisk': 'القرص',
  'si.thUsed': 'المستخدم',
  'si.thFree': 'الحر',

  // ---------- صفحات: المحلّل والمجلدات والتقرير وبدء التشغيل ----------
  'da.stopped': 'أُوقف التحليل',
  'da.failed': 'فشل التحليل: {msg}',
  'da.trashConfirm': 'نقل "{name}" إلى سلة المحذوفات؟',
  'da.trashDetail': '{path}\\nالحجم: {size}',
  'da.moved': 'تم النقل إلى سلة المحذوفات',
  'da.deleteFailed': 'فشل الحذف: {msg}',
  'da.pick': 'اختر مجلدًا أو قرصًا',
  'da.up': 'للأعلى',
  'da.total': 'الإجمالي: {size}',
  'da.empty': 'اختر مجلدًا لترى أين تذهب مساحة القرص بالضبط',
  'da.emptyFolder': 'المجلد فارغ',
  'da.thItem': 'العنصر',
  'da.thShare': 'النسبة',
  'da.thFiles': 'الملفات',
  'da.openIt': 'افتح',
  'ex.noEmpty': 'لا توجد مجلدات فارغة',
  'ex.noBroken': 'لا توجد اختصارات معطوبة',
  'ex.scanFailed': 'فشل الفحص: {msg}',
  'ex.trashConfirm': 'نقل {n} عنصر إلى سلة المحذوفات؟',
  'ex.trashDetail': 'يمكنك استرجاعها من سلة المحذوفات إن غيّرت رأيك.',
  'ex.deleted': 'تم حذف {n} عنصر',
  'ex.modeEmpty': 'المجلدات الفارغة',
  'ex.modeShortcuts': 'الاختصارات المعطوبة',
  'ex.pick': 'اختر مجلدًا وافحص',
  'ex.deleteSel': 'حذف المحدَّد ({n})',
  'ex.emptyHint': 'اختر مجلدًا للبحث عن المجلدات الفارغة تمامًا',
  'ex.shortcutsHint': 'اختر مجلدًا للبحث عن اختصارات اختفى هدفها',
  'ex.thFolder': 'المجلد',
  'ex.thShortcut': 'الاختصار',
  'ex.thTarget': 'الهدف المفقود',
  'rp.failed': 'فشل إنشاء التقرير: {msg}',
  'rp.saved': 'تم حفظ التقرير',
  'rp.copied': 'تم نسخ التقرير',
  'rp.copyFailed': 'تعذّر النسخ',
  'rp.building': 'جارٍ جمع المعلومات…',
  'rp.rebuild': 'إعادة إنشاء التقرير',
  'rp.build': 'إنشاء التقرير',
  'rp.generatedAt': 'أُنشئ {date}',
  'rp.saveFile': 'حفظ كملف',
  'rp.hint': 'يجمع التقرير معلومات النظام والأقراص وما يمكن تنظيفه وبرامج بدء التشغيل والبرامج المثبَّتة في ملف Markdown واحد — مناسب لإرساله للدعم الفني أو لحفظ لقطة عن حالة الجهاز قبل أي تغيير كبير.',
  'rp.empty': 'اضغط "إنشاء التقرير" لجمع لقطة كاملة عن جهازك',
  'su.HKCU-Run': 'المستخدم الحالي (Run)',
  'su.HKLM-Run': 'كل المستخدمين (Run)',
  'su.StartupFolder-User': 'مجلد بدء التشغيل (المستخدم)',
  'su.StartupFolder-Common': 'مجلد بدء التشغيل (مشترك)',
  'su.loadFailed': 'فشل جلب برامج بدء التشغيل: {msg}',
  'su.opFailed': 'فشلت العملية: {msg}',
  'su.deleteConfirm': 'حذف "{name}" نهائيًا من بدء التشغيل؟',
  'su.deleteFailed': 'فشل الحذف: {msg}',
  'su.count': '{n} عنصر',
  'su.thCommand': 'الأمر / المسار',
  'su.thLocation': 'الموقع',
  'su.enabled': 'مفعّل',
  'su.disabled': 'معطّل',
  'su.disable': 'تعطيل',
  'su.enable': 'تفعيل',

  // ---------- صفحات: العمليات والخدمات والشبكة والخصوصية ----------
  'pr.failed': 'تعذّر جلب العمليات: {msg}',
  'pr.killConfirm': 'إنهاء العملية "{name}"؟',
  'pr.killDetail': 'قد تفقد أي عمل غير محفوظ في هذا البرنامج. لا تُنهِ عمليات النظام إن لم تكن متأكدًا.',
  'pr.searchPh': 'ابحث باسم العملية…',
  'pr.sortMem': 'ترتيب حسب الذاكرة',
  'pr.sortCpu': 'ترتيب حسب المعالج',
  'pr.sortName': 'ترتيب حسب الاسم',
  'pr.autoRefresh': 'تحديث تلقائي',
  'pr.count': '{n} عملية — {size}',
  'pr.thPid': 'المعرّف',
  'pr.thMem': 'الذاكرة',
  'pr.thUser': 'المستخدم',
  'pr.kill': 'إنهاء',
  'sv.running': 'يعمل',
  'sv.stopped': 'متوقف',
  'sv.paused': 'موقوف مؤقتًا',
  'sv.unknown': 'غير معروف',
  'sv.boot': 'عند الإقلاع',
  'sv.system': 'نظام',
  'sv.automatic': 'تلقائي',
  'sv.manual': 'يدوي',
  'sv.disabled': 'معطّل',
  'sv.failed': 'تعذّر جلب الخدمات: {msg}',
  'sv.stopConfirm': 'إيقاف الخدمة "{name}"؟',
  'sv.stopDetail': 'إيقاف خدمات النظام قد يعطّل ميزات في ويندوز حتى إعادة تشغيلها.',
  'sv.searchPh': 'ابحث باسم الخدمة…',
  'sv.runningOnly': 'العاملة فقط',
  'sv.count': '{n} خدمة',
  'sv.warn': 'تشغيل الخدمات وإيقافها يتطلب صلاحيات مرتفعة. الخدمات جزء من عمل النظام الداخلي (خدمات ويندوز أو وظائف launchd على ماك)، فلا توقف خدمة لا تعرف وظيفتها.',
  'sv.thService': 'الخدمة',
  'sv.thStartType': 'نوع البدء',
  'sv.stop': 'إيقاف',
  'sv.restart': 'إعادة تشغيل',
  'sv.start': 'تشغيل',
  'nw.failed': 'تعذّر جلب معلومات الشبكة: {msg}',
  'nw.count': '{a} محوّل، {c} اتصال نشط',
  'nw.flushDns': 'مسح ذاكرة DNS',
  'nw.pingTitle': 'اختبار الاتصال',
  'nw.pingPh': 'مثال: google.com',
  'nw.pinging': 'جارٍ الاختبار…',
  'nw.ping': 'اختبر',
  'nw.pingAvg': 'متوسط الاستجابة {ms} مللي ثانية',
  'nw.adapters': 'محوّلات الشبكة',
  'nw.thAdapter': 'المحوّل',
  'nw.thIp': 'عنوان IP',
  'nw.thSpeed': 'السرعة',
  'nw.thTraffic': 'مُنزَّل / مُرسَل',
  'nw.up': 'متصل',
  'nw.down': 'غير متصل',
  'nw.connections': 'الاتصالات النشطة',
  'nw.thApp': 'البرنامج',
  'nw.thProto': 'البروتوكول',
  'nw.thLocal': 'محلي',
  'nw.thRemote': 'بعيد',
  'pv.history.t': 'سجل التصفح',
  'pv.history.d': 'المواقع التي زرتها والأيقونات المخزّنة',
  'pv.cookies.t': 'ملفات تعريف الارتباط',
  'pv.cookies.d': 'ستُسجَّل خروجك من كل المواقع',
  'pv.sessions.t': 'الجلسات المحفوظة',
  'pv.sessions.d': 'التبويبات التي يستعيدها المتصفح عند فتحه',
  'pv.formdata.t': 'بيانات النماذج',
  'pv.formdata.d': 'الإكمال التلقائي للعناوين والبحث',
  'pv.scanFailed': 'فشل الفحص: {msg}',
  'pv.clearConfirm': 'مسح {n} عنصر من بيانات المتصفح؟',
  'pv.cookieWarn': 'ستحتاج لتسجيل الدخول للمواقع مجددًا. ',
  'pv.closeFirst': 'أغلق المتصفحات أولًا وإلا فشل حذف الملفات المستخدَمة.',
  'pv.cleared': 'تم مسح {n} عنصر وتحرير {size}',
  'pv.partial': 'تعذّر {fail} من {n}: {msg}',
  'pv.searching': 'جارٍ البحث عن المتصفحات…',
  'pv.count': '{b} متصفح، {n} عنصر',
  'pv.clearing': 'جارٍ المسح…',
  'pv.clearSel': 'مسح المحدَّد ({size})',
  'pv.note': 'أغلق المتصفح قبل المسح، فملفاته تكون مقفلة أثناء عمله. المفضّلة وكلمات المرور المحفوظة لا تُمسّ أبدًا. في فايرفوكس لا نعرض سجل التصفح لأنه محفوظ في الملف نفسه مع المفضّلة.',
  'pv.none': 'لم يُعثر على بيانات متصفحات على هذا الجهاز',

  // ---------- صفحات: التنزيلات والممزّق وأدوات ماك ----------
  'od.trashConfirm': 'نقل {n} عنصر إلى المهملات؟',
  'od.trashDetail': 'سيتحرّر نحو {size}. يمكنك استرجاعها من المهملات.',
  'od.partial': 'حُذف {ok}، وتعذّر {fail}',
  'od.moved': 'تم نقل {n} عنصر إلى المهملات',
  'od.olderThan': 'أقدم من',
  'od.openFolder': 'فتح مجلد التنزيلات',
  'od.clearAll': 'إلغاء تحديد الكل',
  'od.trashBtn': 'نقل إلى المهملات ({size})',
  'od.oldItems': 'عناصر قديمة',
  'od.theirSize': 'حجمها الإجمالي',
  'od.oldest': 'الأقدم',
  'od.daysN': '{n} يوم',
  'od.none': 'لا شيء أقدم من {n} يومًا في مجلد التنزيلات',
  'od.thModified': 'آخر تعديل',
  'od.thAge': 'العمر',
  'sh.confirm': 'تمزيق {n} عنصر نهائيًا؟',
  'sh.confirmDetail': 'لا يمكن التراجع ولا الاسترجاع من المهملات — سيُكتب فوق المحتوى قبل الحذف.',
  'sh.partial': 'اكتمل مع تعذّر {n} ملف',
  'sh.done': 'تم تمزيق {n} ملف نهائيًا',
  'sh.failed': 'فشل التمزيق: {msg}',
  'sh.warnBold': 'الحذف هنا نهائي ولا يمر بالمهملات.',
  'sh.warnBody': 'يُكتب فوق محتوى الملف ببيانات عشوائية ثم أصفار قبل حذفه، فيصعب استرجاعه ببرامج الاسترداد. على أقراص SSD قد يبقي القرص نسخًا داخلية، فالتمزيق يقلّل الاحتمال ولا يضمن.',
  'sh.addFiles': 'إضافة ملفات',
  'sh.addFolder': 'إضافة مجلد',
  'sh.passes': 'مرات الكتابة',
  'sh.running': 'جارٍ التمزيق…',
  'sh.shredBtn': 'تمزيق {n} نهائيًا',
  'sh.progress': 'الملف {i} من {n} — المرور {p}/{tp}',
  'sh.preparing': 'جارٍ التحضير…',
  'sh.stop': 'إيقاف',
  'sh.empty': 'أضف ملفات أو مجلدات تريد إتلافها بحيث لا يمكن استرجاعها',
  'sh.waiting': 'في الانتظار',
  'sh.shredded': 'مُزِّق',
  'sh.removeFromList': 'إزالة من القائمة',
  'mt.noOrphans': 'لا توجد مخلّفات يتيمة',
  'mt.noLangs': 'لا توجد ملفات لغات قابلة للحذف',
  'mt.scanFailed': 'فشل الفحص: {msg}',
  'mt.trashConfirm': 'نقل {n} عنصر إلى المهملات؟',
  'mt.trashDetail': 'سيتحرّر نحو {size}. يمكنك استرجاعها من المهملات.',
  'mt.partial': 'حُذف {ok}، وتعذّر {fail} (قد تحتاج صلاحيات)',
  'mt.deleted': 'تم حذف {n} عنصر',
  'mt.modeOrphans': 'مخلّفات تطبيقات محذوفة',
  'mt.modeLanguages': 'ملفات اللغات غير المستخدمة',
  'mt.startScan': 'ابدأ الفحص',
  'mt.purge': 'تحرير الذاكرة',
  'mt.deleteSel': 'حذف المحدَّد ({size})',
  'mt.orphansNote': 'سحب تطبيق إلى المهملات على ماك لا يحذف ما تركه في Library. هنا نعرض ملفات دعم لتطبيقات لم تعد مثبَّتة — راجعها قبل الحذف، فالمطابقة بالاسم قد تُخطئ أحيانًا.',
  'mt.langsNote': 'تحمل معظم التطبيقات عشرات اللغات التي لن تستخدمها. نُبقي دائمًا الإنجليزية والعربية، ونعرض الباقي. قد يعيد تحديث التطبيق إضافتها.',
  'mt.empty': 'اضغط "ابدأ الفحص" لبدء البحث',
  'mt.thItem': 'العنصر',
  'mt.thApp': 'التطبيق',
  'mt.thLocation': 'الموقع',
  'mt.thLangCount': 'عدد اللغات',
  'mt.langsN': '{n} لغة',

  // ---------- صفحات: إزالة البرامج ومدير الملفات ----------
  'un.loadFailed': 'فشل جلب قائمة البرامج: {msg}',
  'un.confirm': 'إزالة "{name}"؟',
  'un.confirmDetail': 'سيتم تشغيل أداة إزالة البرنامج الرسمية الخاصة به. قد تظهر نافذة تأكيد إضافية منها.',
  'un.removed': 'تمت إزالة {name}',
  'un.removeFailed': 'تعذّرت الإزالة: {msg}',
  'un.leftoverConfirm': 'حذف المجلد المتبقّي؟',
  'un.leftoverDetail': '{path}\\nسيُحذف نهائيًا ({size}).',
  'un.leftoverDeleted': 'تم حذف المخلّفات',
  'un.deleteFailed': 'فشل الحذف: {msg}',
  'un.searchPh': 'ابحث باسم البرنامج أو الناشر…',
  'un.count': '{n} برنامج',
  'un.thPublisher': 'الناشر',
  'un.thVersion': 'الإصدار',
  'un.thSize': 'الحجم التقديري',
  'un.thInstalled': 'تاريخ التثبيت',
  'un.busy': 'جارٍ…',
  'un.uninstall': 'إزالة',
  'un.leftovers': 'مخلّفات',
  'un.leftoversTitle': 'مخلّفات "{name}"',
  'un.searching': 'جارٍ البحث عن مجلدات متبقّية…',
  'un.noLeftovers': 'لا توجد مخلّفات ظاهرة لهذا البرنامج.',
  'fm.searchStopped': 'أُوقف البحث',
  'fm.searchFailed': 'فشل البحث: {msg}',
  'fm.openFailed': 'تعذّر فتح المسار: {msg}',
  'fm.trashConfirm': 'نقل {n} عنصر إلى سلة المحذوفات؟',
  'fm.trashDetail': 'يمكنك استعادتها لاحقًا من سلة المحذوفات.',
  'fm.trashedPartial': 'تم الحذف مع {n} فشل',
  'fm.trashed': 'تم النقل إلى سلة المحذوفات',
  'fm.renameFailed': 'فشل إعادة التسمية: {msg}',
  'fm.mkdirFailed': 'فشل إنشاء المجلد: {msg}',
  'fm.newFolder': 'مجلد جديد',
  'fm.toTrash': 'نقل إلى سلة المحذوفات',
  'fm.batchRename': 'إعادة تسمية دفعية',
  'fm.searchPh': 'ابحث داخل هذا المجلد وما تحته…',
  'fm.clearSearch': 'إلغاء نتائج البحث',
  'fm.selectedN': 'محدَّد: {n}',
  'fm.drives': 'الأقراص',
  'fm.noMatches': 'لا نتائج مطابقة',
  'fm.searchResults': 'نتائج البحث ({n})',
  'fm.emptyFolder': 'المجلد فارغ',
  'fm.rename': 'إعادة تسمية',
  'fm.newFolderTitle': 'اسم المجلد الجديد',
  'fm.create': 'إنشاء',

  // ---------- صفحة وسوم الأغاني ----------
  'tg.readFailed': 'فشل قراءة المجلد: {msg}',
  'tg.savePartial': '{fail} فشل من {n}',
  'tg.saved': 'تم الحفظ',
  'tg.renamed': 'تمت إعادة تسمية {ok} من {n}',
  'tg.noMatch': 'لم يتطابق أي ملف مع النمط',
  'tg.filled': 'تم تعبئة وحفظ وسوم {n} ملف من الاسم',
  'tg.pickFolder': 'اختر مجلد أغاني',
  'tg.reading': 'جارٍ القراءة…',
  'tg.empty': 'اختر مجلدًا يحتوي على ملفات صوتية لعرض وتحرير وسومها',
  'tg.thFile': 'الملف',
  'tg.artist': 'الفنان',
  'tg.title': 'العنوان',
  'tg.duration': 'المدة',
  'tg.pickOne': 'اختر ملفًا واحدًا أو أكثر من القائمة لتحرير وسومه',
  'tg.nSelected': '{n} ملفات محدَّدة',
  'tg.batchNote': 'الحقول الفارغة لن تُغيَّر — عبّئ فقط ما تريد تطبيقه على كل الملفات المحدَّدة',
  'tg.album': 'الألبوم',
  'tg.albumArtist': 'فنان الألبوم',
  'tg.year': 'السنة',
  'tg.track': 'الرقم',
  'tg.genre': 'النوع',
  'tg.comment': 'ملاحظة',
  'tg.changeCover': 'تغيير الغلاف',
  'tg.coverChosen': 'سيتم استخدام الصورة المختارة',
  'tg.saving': 'جارٍ الحفظ…',
  'tg.saveTags': 'حفظ الوسوم',
  'tg.mp3Only': 'الحفظ بالكتابة مدعوم حاليًا لملفات MP3 فقط.',
  'tg.renameFromTags': 'إعادة تسمية من الوسوم',
  'tg.applyFolder': 'تطبيق على المجلد',
  'tg.fillFromName': 'تعبئة الوسوم من اسم الملف (كل المجلد)',
  'tg.patternExample': 'مثال: %artist% - %title% يطابق "Fairuz - Nassam Alayna.mp3"',

  // ---------- الذكاء الاصطناعي ----------
  'page.assistant': 'المساعد الذكي',
  'page.assistant.sub': 'اسأل عن جهازك بلغتك، ويقرأ حالته ويقترح ما تفعله',
  'ai.title': 'المساعد الذكي',
  'ai.placeholder': 'اسأل عن أي شيء في جهازك…',
  'ai.send': 'إرسال',
  'ai.stop': 'إيقاف',
  'ai.clear': 'محادثة جديدة',
  'ai.thinking': 'يفحص جهازك…',
  'ai.disabledTitle': 'مميزات الذكاء الاصطناعي معطّلة',
  'ai.disabledBody': 'فعّلها من الإعدادات وأضف مفتاح Anthropic الخاص بك. تعمل بمفتاحك أنت وتُحاسَب عليه مباشرةً من Anthropic — لا يمرّ شيء عبر خوادمنا.',
  'ai.noKeyTitle': 'لا يوجد مفتاح',
  'ai.noKeyBody': 'أضف مفتاح Anthropic من الإعدادات لتشغيل المساعد.',
  'ai.openSettings': 'فتح الإعدادات',
  'ai.privacy': 'يُرسَل للنموذج وصفٌ فقط: أسماء المجلدات والملفات وأحجامها وأعدادها. لا يُقرأ محتوى أي ملف ولا يُرسَل.',
  'ai.cannotDelete': 'المساعد يقرأ ويقترح فقط — الحذف يبقى بيدك من صفحات التطبيق.',
  'ai.err.auth': 'المفتاح مرفوض. راجعه في الإعدادات.',
  'ai.err.rate': 'تجاوزت حدّ الطلبات — أعد المحاولة بعد قليل.',
  'ai.err.offline': 'تعذّر الاتصال. تحقّق من الإنترنت.',
  'ai.err.refusal': 'امتنع النموذج عن الإجابة على هذا الطلب.',
  'ai.err.generic': 'تعذّر إكمال الطلب: {msg}',
  'ai.err.noKey': 'لا يوجد مفتاح محفوظ.',
  'ai.cancelled': 'أُوقف الطلب.',
  'ai.usage': '{in} رمز دخْل • {out} رمز خرْج',
  'ai.tool.get_device_health': 'يقرأ درجة صحة الجهاز',
  'ai.tool.scan_cleanable': 'يفحص ما يمكن تنظيفه',
  'ai.tool.get_system_summary': 'يقرأ معلومات النظام',
  'ai.tool.analyze_folder': 'يحلّل مجلدًا',
  'ai.tool.find_large_files': 'يبحث عن أكبر الملفات',
  'ai.tool.list_startup_items': 'يقرأ برامج بدء التشغيل',
  'ai.tool.list_installed_apps': 'يقرأ البرامج المثبَّتة',
  'ai.tool.list_processes': 'يقرأ العمليات العاملة',
  'ai.tool.find_old_downloads': 'يبحث في التنزيلات القديمة',
  'ai.tool.get_clean_history': 'يقرأ سجل التنظيف',
  'ai.sug.why': 'لماذا امتلأ قرصي؟',
  'ai.sug.safe': 'ما الذي يمكنني حذفه بأمان الآن؟',
  'ai.sug.slow': 'لماذا جهازي بطيء؟',
  'ai.sug.startup': 'راجع برامج بدء التشغيل عندي',
  'ai.explainBtn': 'اشرح لي',
  'ai.explaining': 'يشرح…',
  'ai.explainProcess': 'ما هذه العملية وهل يمكن إنهاؤها؟',
  'ai.explainCategory': 'ما هذه الفئة وهل حذفها آمن؟',
  'ai.explainFoot': 'جواب من نموذج ذكاء اصطناعي — راجعه قبل التنفيذ.',
  'ai.smartTags': 'تعبئة ذكية',
  'ai.smartTagsBusy': 'يستنتج…',
  'ai.smartTagsHint': 'يستنتج الفنان والعنوان والألبوم من اسم الملف فقط.',
  'ai.smartTagsFail': 'تعذّر استنتاج البيانات من اسم الملف.',
  'ai.smartTagsDone': 'عُبّئت الحقول — راجعها قبل الحفظ.',
  'set.ai': 'الذكاء الاصطناعي',
  'set.ai.sub': 'مساعد يقرأ حالة جهازك ويشرح ويقترح — بمفتاحك الخاص',
  'set.ai.enable': 'تفعيل مميزات الذكاء الاصطناعي',
  'set.ai.enableSub': 'معطّلة افتراضيًا. عند التفعيل تُرسَل بيانات وصفية عن جهازك إلى Anthropic.',
  'set.ai.key': 'مفتاح Anthropic',
  'set.ai.keySub': 'يُخزَّن مشفَّرًا في سلسلة مفاتيح نظامك ولا يظهر في الواجهة بعد الحفظ.',
  'set.ai.keyPlaceholder': 'sk-ant-…',
  'set.ai.saved': 'المفتاح محفوظ ({hint})',
  'set.ai.save': 'حفظ المفتاح',
  'set.ai.saving': 'يتحقّق…',
  'set.ai.remove': 'حذف المفتاح',
  'set.ai.removed': 'حُذف المفتاح',
  'set.ai.ok': 'المفتاح يعمل وحُفظ',
  'set.ai.model': 'الطراز',
  'set.ai.modelSub': 'الأقوى أدقّ وأغلى؛ الأسرع أرخص ويكفي للأسئلة البسيطة.',
  'set.ai.getKey': 'احصل على مفتاح من console.anthropic.com',
  'set.ai.noEncryption': 'سلسلة مفاتيح النظام غير متاحة هنا، فسيُخزَّن المفتاح بلا تشفير قوي.',
  'set.ai.cost': 'التكلفة على حسابك لدى Anthropic مباشرةً، بحسب ما تستهلكه.'
}
