/** القاموس العربي — مفاتيح مشتركة ثم مفاتيح كل صفحة. */
export const AR: Record<string, string> = {
  // ---------- عام ----------
  'app.name': 'CleanShelf',
  'app.by': 'من تطوير Alcode',
  'app.byShort': 'من تطوير {company}',

  'common.cancel': 'إلغاء',
  'common.confirm': 'تأكيد',
  'common.save': 'حفظ',
  'common.saving': 'جارٍ الحفظ…',
  'common.delete': 'حذف',
  'common.remove': 'إزالة',
  'common.close': 'إغلاق',
  'common.apply': 'تطبيق',
  'common.open': 'فتح',
  'common.refresh': 'تحديث',
  'common.rescan': 'إعادة الفحص',
  'common.scan': 'فحص',
  'common.scanning': 'جارٍ الفحص…',
  'common.stopScan': 'إيقاف الفحص',
  'common.loading': 'جارٍ التحميل…',
  'common.search': 'بحث',
  'common.searchQuick': 'بحث سريع…',
  'common.selectAll': 'تحديد الكل',
  'common.clearAll': 'إلغاء التحديد',
  'common.selected': 'محدَّد',
  'common.viewAll': 'عرض الكل',
  'common.viewDetails': 'عرض التفاصيل',
  'common.details': 'تفاصيل',
  'common.name': 'الاسم',
  'common.size': 'الحجم',
  'common.date': 'التاريخ',
  'common.path': 'المسار',
  'common.status': 'الحالة',
  'common.type': 'النوع',
  'common.free': 'متاحة',
  'common.used': 'مستخدمة',
  'common.total': 'الإجمالي',
  'common.item': 'عنصر',
  'common.items': 'عنصر',
  'common.file': 'ملف',
  'common.files': 'ملف',
  'common.day': 'يوم',
  'common.days': 'يوم',
  'common.hours': 'ساعة',
  'common.category': 'فئة',
  'common.categories': 'فئة',
  'common.nothing': 'لا شيء',
  'common.empty': 'لا شيء هنا',
  'common.failed': 'تعذّر إتمام العملية',
  'common.settings': 'الإعدادات',
  'common.back': 'رجوع',
  'common.retry': 'إعادة المحاولة',
  'common.copy': 'نسخ',
  'common.copied': 'تم النسخ',

  'unit.b': 'بايت',
  'unit.kb': 'كيلوبايت',
  'unit.mb': 'ميغابايت',
  'unit.gb': 'غيغابايت',
  'unit.tb': 'تيرابايت',

  // ---------- الشريط الجانبي والعناوين ----------
  'nav.disk': 'أدوات القرص',
  'nav.privacy': 'الخصوصية والأمان',
  'nav.system': 'النظام',
  'nav.pin': 'تثبيت في الرئيسية',
  'nav.unpin': 'إلغاء التثبيت',

  'page.dashboard': 'الرئيسية',
  'page.dashboard.sub': 'نظرة عامة على صحة جهازك وتنظيف بضغطة واحدة',
  'page.overview': 'نظرة عامة',
  'page.overview.sub': 'توقّع امتلاء القرص وأكبر فرص التنظيف',
  'page.plan': 'خطة الصيانة',
  'page.plan.sub': 'مهام دورية تحافظ على جهازك نظيفًا',
  'page.cleaner': 'منظّف القرص',
  'page.cleaner.sub': 'حرّر المساحة بحذف الملفات غير الضرورية',
  'page.uninstaller': 'إزالة البرامج',
  'page.uninstaller.sub': 'أزل البرامج المثبَّتة مع مخلّفاتها',
  'page.files': 'مدير الملفات',
  'page.files.sub': 'تصفّح وأعد تسمية ونظّم ملفاتك',
  'page.tags': 'محرر وسوم الأغاني',
  'page.tags.sub': 'حرّر معلومات وأغلفة ملفات MP3 كما في Mp3tag',
  'page.duplicates': 'الملفات المكرّرة',
  'page.duplicates.sub': 'اعثر على النسخ المكرّرة واسترجع المساحة',
  'page.largefiles': 'أكبر الملفات',
  'page.largefiles.sub': 'حدّد أكبر الملفات المستهلكة للمساحة',
  'page.startup': 'برامج بدء التشغيل',
  'page.startup.sub': 'تحكّم بما يعمل تلقائيًا عند إقلاع الجهاز',
  'page.system': 'معلومات النظام',
  'page.system.sub': 'حالة المعالج والذاكرة والأقراص',
  'page.processes': 'العمليات',
  'page.processes.sub': 'ما يعمل الآن على جهازك، وإنهاء ما تريد',
  'page.services': 'خدمات النظام',
  'page.services.sub': 'تشغيل وإيقاف خدمات النظام وlaunchd',
  'page.network': 'الشبكة',
  'page.network.sub': 'المحوّلات والاتصالات النشطة وأدوات التشخيص',
  'page.diskanalyzer': 'محلّل المساحة',
  'page.diskanalyzer.sub': 'اعرف أين تذهب مساحة قرصك بالضبط',
  'page.extras': 'مجلدات واختصارات',
  'page.extras.sub': 'المجلدات الفارغة والاختصارات المعطوبة',
  'page.history': 'سجل التنظيف',
  'page.history.sub': 'ما نُظّف سابقًا وكم مساحة تحرّرت',
  'page.mactools': 'أدوات ماك',
  'page.mactools.sub': 'مخلّفات التطبيقات المحذوفة وملفات اللغات',
  'page.privacy': 'خصوصية المتصفح',
  'page.privacy.sub': 'امسح سجل التصفح والكوكيز والجلسات من كل المتصفحات',
  'page.shredder': 'الممزّق الآمن',
  'page.shredder.sub': 'احذف الملفات الحساسة بحيث يستحيل استرجاعها',
  'page.downloads': 'التنزيلات القديمة',
  'page.downloads.sub': 'ما نسيته في مجلد التنزيلات منذ شهور',
  'page.report': 'تقرير النظام',
  'page.report.sub': 'لقطة كاملة عن جهازك قابلة للحفظ والمشاركة',
  'page.settings': 'الإعدادات',
  'page.settings.sub': 'المظهر واللغة والسلوك وخيارات الأدوات',

  // ---------- لوحة الأوامر ----------
  'palette.pages': 'الصفحات',
  'palette.actions': 'إجراءات',
  'palette.placeholder': 'اكتب اسم صفحة أو إجراء…',
  'palette.noResults': 'لا نتائج',
  'palette.smartClean': 'تنظيف ذكي الآن',
  'palette.theme': 'تبديل المظهر (الحالي: {mode})',
  'palette.lang': 'تبديل اللغة (الحالية: {lang})',
  'palette.report': 'إنشاء تقرير عن الجهاز',
  'palette.hintOpen': 'للفتح',
  'palette.hintMove': 'للتنقّل',

  // ---------- المظهر ----------
  'theme.system': 'حسب النظام',
  'theme.light': 'فاتح',
  'theme.dark': 'داكن',
  'theme.tip': 'المظهر: {mode} — اضغط للتبديل',

  // ---------- الرئيسية ----------
  'dash.period.week': 'هذا الأسبوع',
  'dash.period.month': 'هذا الشهر',
  'dash.period.year': 'هذه السنة',
  'dash.mainDisk': 'القرص الرئيسي',
  'dash.planTile': 'خطة الصيانة',
  'dash.diskTile': 'حالة القرص',
  'dash.overdue': 'متأخرة',
  'dash.due': 'مستحقة',
  'dash.inPlan': 'في الخطة',
  'dash.done': 'منجزة',
  'dash.seg.used': 'مستخدمة',
  'dash.seg.junk': 'قابلة للتنظيف',
  'dash.seg.free': 'متاحة',
  'dash.totalOf': '{unit} الإجمالي',
  'dash.outOf100': 'من 100',
  'dash.smartClean': 'تنظيف ذكي بضغطة واحدة',
  'dash.cleaning': 'جارٍ التنظيف الذكي…',
  'dash.scanDevice': 'فحص الجهاز',
  'dash.factors': 'عوامل الصحة',
  'dash.pinnedTools': 'أدواتك المثبَّتة',
  'dash.quickTools': 'أدوات سريعة',
  'dash.allTools': 'كل الأدوات',
  'dash.lastCleans': 'آخر عمليات التنظيف',
  'dash.cpu': 'المعالج',
  'dash.memUsed': 'الذاكرة المستخدمة',
  'dash.diskFree': 'المساحة المتاحة',
  'dash.uptime': 'مدة التشغيل',
  'dash.outOfTotal': 'من أصل {size}',
  'dash.ofTotal': 'من {size}',
  'dash.hoursShort': '{n} ساعة',

  'health.evaluating': 'جارٍ تقييم جهازك…',
  'health.excellent': 'جهازك بحالة ممتازة',
  'health.good': 'جهازك بحالة جيدة',
  'health.fair': 'جهازك يحتاج بعض العناية',
  'health.poor': 'جهازك يحتاج تنظيفًا الآن',
  'health.canFree': 'يمكن تحرير نحو {size} بضغطة واحدة دون أي مخاطرة.',
  'health.clean': 'لا توجد ملفات غير ضرورية تستحق التنظيف الآن.',
  'health.scanningDesc': 'نفحص الملفات المؤقتة والذاكرة والقرص وبرامج بدء التشغيل…',
  'health.idleDesc': 'اضغط "فحص الجهاز" لتقييم حالته الحالية.',
  'health.failed': 'تعذّر تقييم الجهاز: {msg}',
  'dash.cleanNothing': 'لا شيء يحتاج تنظيفًا — جهازك نظيف',
  'dash.cleanDone': 'تم تحرير {size} من {n} فئة',
  'dash.cleanFailed': 'فشل التنظيف الذكي: {msg}',

  // ---------- نظرة عامة ----------
  'ov.measuring': 'نقيس مساحة قرصك…',
  'ov.almostFull': 'قرصك على وشك الامتلاء',
  'ov.shrinking': 'مساحة قرصك تتناقص',
  'ov.healthy': 'مساحة قرصك بحالة جيدة',
  'ov.freeSpace': 'المساحة المتاحة',
  'ov.perDay': 'يُستهلك يوميًا',
  'ov.perDayDesc': 'متوسط ما تستهلكه مساحتك كل يوم',
  'ov.needDays': 'نحتاج بضعة أيام من القياسات',
  'ov.forecast': 'توقّع امتلاء القرص',
  'ov.forecastDesc': 'يُحسب من قياسات الأيام السابقة',
  'ov.forecastIn': 'بهذا المعدّل يمتلئ القرص بعد نحو {n} يومًا',
  'ov.biggest': 'أكبر فرصة تنظيف',
  'ov.highImpact': 'أثر كبير',
  'ov.others': 'فرص أخرى',
  'ov.planTasks': 'مهام الخطة',
  'ov.allDone': 'كل مهام الخطة منجزة — جهازك في أفضل حال',
  'ov.junkDetail': '{size} من الملفات المؤقتة والذواكر',
  'ov.dupDetail': 'نسخ متطابقة تهدر المساحة بلا فائدة',
  'ov.largeDetail': 'أكبر الملفات المستهلكة للمساحة',
  'ov.dlDetail': 'ما نسيته في مجلد التنزيلات منذ شهور',

  // ---------- خطة الصيانة ----------
  'plan.never': 'لم تُنفَّذ بعد',
  'plan.today': 'نُفِّذت اليوم',
  'plan.daysAgo': 'آخر مرة قبل {n} يوم',
  'plan.every': 'كل {n} يوم',
  'plan.markDone': 'تسجيلها كمنجزة',
  'plan.marked': 'سُجّلت "{label}" كمنجزة',
  'plan.badge.overdue': 'متأخرة',
  'plan.badge.due': 'مستحقة',
  'plan.badge.done': 'منجزة',
  'plan.task.junk': 'تنظيف الملفات غير الضرورية',
  'plan.task.privacy': 'مسح بيانات التصفح',
  'plan.task.downloads': 'ترتيب مجلد التنزيلات',
  'plan.task.duplicates': 'إزالة الملفات المكرّرة',
  'plan.task.largefiles': 'مراجعة أكبر الملفات',
  'plan.task.startup': 'مراجعة برامج بدء التشغيل',
  'plan.task.uninstaller': 'إزالة البرامج غير المستخدمة',
  'plan.task.extras': 'حذف المجلدات الفارغة والاختصارات المعطوبة',

  // ---------- الإعدادات ----------
  'set.language': 'اللغة',
  'set.language.sub': 'يتغيّر اتجاه الواجهة تلقائيًا',
  'set.arabic': 'العربية',
  'set.english': 'English',
  'set.appearance': 'المظهر',
  'set.theme': 'السمة',
  'set.accent': 'لون التمييز',
  'set.accent.sub': 'الأزرار والعناصر النشطة',
  'set.behavior': 'السلوك',
  'set.tray': 'التصغير إلى شريط النظام',
  'set.tray.sub': 'يبقى التطبيق عاملًا عند إغلاق النافذة',
  'set.launch': 'التشغيل عند بدء النظام',
  'set.launch.sub': 'يفتح التطبيق تلقائيًا بعد تسجيل الدخول',
  'set.notif': 'إشعار عند اكتمال التنظيف',
  'set.notif.sub': 'يظهر ما تحرّر من مساحة',
  'set.autoscan': 'فحص تلقائي عند الفتح',
  'set.autoscan.sub': 'يحسب درجة الصحة فور فتح التطبيق',
  'set.tools': 'الأدوات',
  'set.dlAge': 'عمر التنزيل القديم',
  'set.shredPasses': 'مرات الكتابة في الممزّق',
  'set.once': 'مرة',
  'set.times': '{n} مرات',
  'set.daysN': '{n} يوم',
  'set.about': 'حول التطبيق',
  'set.saveFailed': 'تعذّر حفظ الإعداد: {msg}',
  'set.shortcuts': 'اختصارات لوحة المفاتيح',
  'set.sc.palette': 'لوحة الأوامر',
  'set.sc.settings': 'الإعدادات',
  'set.sc.theme': 'تبديل المظهر',

  // ---------- مكوّنات مشتركة ----------
  'palette.empty': 'لا نتائج لـ "{q}"',
  'palette.kMove': 'تنقّل',
  'palette.kOpen': 'فتح',
  'palette.kClose': 'إغلاق',
  'batch.title': 'إعادة تسمية دفعية ({n} ملف)',
  'batch.hint': 'استخدم %name% للاسم الأصلي، %n% للترقيم التسلسلي، %ext% للامتداد',
  'batch.start': 'رقم البداية',
  'batch.applying': 'جارٍ التنفيذ…',
  'batch.done': 'تمت إعادة تسمية {n} ملف',
  'batch.partial': 'تمت إعادة تسمية {n} ملف، وتعذّر {fail} ({msg})',
  'batch.failed': 'فشل بعض العمليات: {msg}',
  'scan.hashing': 'مقارنة محتوى الملفات… {i} من {n}',
  'scan.walking': 'جارٍ فحص المجلدات… {n} ملف',

  // ---------- الإعدادات (تفصيل) ----------
  'set.appearance.sub': 'اختر ما يريح عينك — يُحفظ تلقائيًا',
  'set.theme.sub': '"حسب النظام" تتبع إعداد {os} تلقائيًا',
  'set.accent.sub2': 'يغيّر لون البطاقات والأزرار في كل التطبيق',
  'set.behavior.sub': 'كيف يتصرف التطبيق في الخلفية',
  'set.tray.sub2': 'إغلاق النافذة يخفيها بدل إنهاء التطبيق، ويبقى التنظيف الذكي متاحًا من الأيقونة',
  'set.launch.sub2': 'يبدأ CleanShelf مخفيًا مع النظام (يعمل في النسخة المثبَّتة فقط)',
  'set.notif.sub2': 'تنبيه عند اكتمال التنظيف بما تحرّر من مساحة',
  'set.autoscan.sub2': 'يحسب درجة الصحة تلقائيًا — أوقفه إن كان الفحص بطيئًا على جهازك',
  'set.tools.sub': 'إعدادات افتراضية للأدوات',
  'set.dlAge.sub': 'الملفات الأقدم من هذا العدد من الأيام تُعرض في أداة التنزيلات القديمة',
  'set.shred.sub': 'أكثر = أبطأ وأصعب استرجاعًا؛ 3 مرات كافية لمعظم الاستخدامات',
  'set.shred.1': 'مرة واحدة (سريع)',
  'set.shred.3': '3 مرات (موصى به)',
  'set.shred.7': '7 مرات (أقصى حماية)',
  'set.forWinMac': 'لويندوز وماك',
  'set.checkUpdate': 'التحقق من وجود إصدار أحدث',
  'os.windows': 'ويندوز',
  'os.mac': 'ماك'
}
