/** The English dictionary — mirrors dict.ar.ts key for key. */
export const EN: Record<string, string> = {
  // ---------- common ----------
  'app.name': 'CleanShelf',
  'app.by': 'by Alcode',
  'app.byShort': 'by {company}',

  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.save': 'Save',
  'common.saving': 'Saving…',
  'common.delete': 'Delete',
  'common.remove': 'Remove',
  'common.close': 'Close',
  'common.apply': 'Apply',
  'common.open': 'Open',
  'common.refresh': 'Refresh',
  'common.rescan': 'Scan again',
  'common.scan': 'Scan',
  'common.scanning': 'Scanning…',
  'common.stopScan': 'Stop scan',
  'common.loading': 'Loading…',
  'common.search': 'Search',
  'common.searchQuick': 'Quick search…',
  'common.selectAll': 'Select all',
  'common.clearAll': 'Clear selection',
  'common.selected': 'Selected',
  'common.viewAll': 'View all',
  'common.viewDetails': 'View details',
  'common.details': 'Details',
  'common.name': 'Name',
  'common.size': 'Size',
  'common.date': 'Date',
  'common.path': 'Path',
  'common.status': 'Status',
  'common.type': 'Type',
  'common.free': 'free',
  'common.used': 'used',
  'common.total': 'Total',
  'common.item': 'item',
  'common.items': 'items',
  'common.file': 'file',
  'common.files': 'files',
  'common.day': 'day',
  'common.days': 'days',
  'common.hours': 'hours',
  'common.category': 'category',
  'common.categories': 'categories',
  'common.nothing': 'Nothing',
  'common.empty': 'Nothing here',
  'common.failed': 'Something went wrong',
  'common.settings': 'Settings',
  'common.back': 'Back',
  'common.retry': 'Try again',
  'common.copy': 'Copy',
  'common.copied': 'Copied',

  'unit.b': 'B',
  'unit.kb': 'KB',
  'unit.mb': 'MB',
  'unit.gb': 'GB',
  'unit.tb': 'TB',

  // ---------- sidebar and page titles ----------
  'nav.disk': 'Disk tools',
  'nav.privacy': 'Privacy & security',
  'nav.system': 'System',
  'nav.pin': 'Pin to the dashboard',
  'nav.unpin': 'Unpin',

  'page.dashboard': 'Dashboard',
  'page.dashboard.sub': 'Your machine at a glance, and a one-click clean',
  'page.overview': 'Overview',
  'page.overview.sub': 'Disk forecast and your biggest cleanup wins',
  'page.plan': 'Maintenance plan',
  'page.plan.sub': 'Recurring tasks that keep your machine tidy',
  'page.cleaner': 'Disk cleaner',
  'page.cleaner.sub': 'Free up space by deleting what you do not need',
  'page.uninstaller': 'Uninstall programs',
  'page.uninstaller.sub': 'Remove installed programs along with their leftovers',
  'page.files': 'File manager',
  'page.files.sub': 'Browse, rename and organise your files',
  'page.tags': 'Music tag editor',
  'page.tags.sub': 'Edit MP3 tags and cover art, Mp3tag style',
  'page.duplicates': 'Duplicate files',
  'page.duplicates.sub': 'Find identical copies and win the space back',
  'page.largefiles': 'Largest files',
  'page.largefiles.sub': 'Spot the files eating the most space',
  'page.startup': 'Startup programs',
  'page.startup.sub': 'Control what runs automatically at boot',
  'page.system': 'System info',
  'page.system.sub': 'CPU, memory and disk status',
  'page.processes': 'Processes',
  'page.processes.sub': 'What is running right now, and how to end it',
  'page.services': 'System services',
  'page.services.sub': 'Start and stop Windows services and launchd jobs',
  'page.network': 'Network',
  'page.network.sub': 'Adapters, live connections and diagnostics',
  'page.diskanalyzer': 'Space analyser',
  'page.diskanalyzer.sub': 'See exactly where your disk space goes',
  'page.extras': 'Folders & shortcuts',
  'page.extras.sub': 'Empty folders and broken shortcuts',
  'page.history': 'Cleaning history',
  'page.history.sub': 'What was cleaned before and how much it freed',
  'page.mactools': 'Mac tools',
  'page.mactools.sub': 'Leftovers of deleted apps and language files',
  'page.privacy': 'Browser privacy',
  'page.privacy.sub': 'Clear history, cookies and sessions from every browser',
  'page.shredder': 'Secure shredder',
  'page.shredder.sub': 'Destroy sensitive files beyond recovery',
  'page.downloads': 'Old downloads',
  'page.downloads.sub': 'What you forgot in Downloads months ago',
  'page.report': 'System report',
  'page.report.sub': 'A full snapshot of your machine you can save or share',
  'page.settings': 'Settings',
  'page.settings.sub': 'Appearance, language, behaviour and tool options',

  // ---------- command palette ----------
  'palette.pages': 'Pages',
  'palette.actions': 'Actions',
  'palette.placeholder': 'Type a page or an action…',
  'palette.noResults': 'No results',
  'palette.smartClean': 'Smart clean now',
  'palette.theme': 'Switch theme (currently: {mode})',
  'palette.lang': 'Switch language (currently: {lang})',
  'palette.report': 'Build a system report',
  'palette.hintOpen': 'to open',
  'palette.hintMove': 'to move',

  // ---------- appearance ----------
  'theme.system': 'System',
  'theme.light': 'Light',
  'theme.dark': 'Dark',
  'theme.tip': 'Theme: {mode} — click to switch',

  // ---------- dashboard ----------
  'dash.period.week': 'This week',
  'dash.period.month': 'This month',
  'dash.period.year': 'This year',
  'dash.mainDisk': 'Main disk',
  'dash.planTile': 'Maintenance plan',
  'dash.diskTile': 'Disk status',
  'dash.overdue': 'Overdue',
  'dash.due': 'Due now',
  'dash.inPlan': 'In plan',
  'dash.done': 'Completed',
  'dash.seg.used': 'Used',
  'dash.seg.junk': 'Cleanable',
  'dash.seg.free': 'Free',
  'dash.totalOf': '{unit} total',
  'dash.outOf100': 'out of 100',
  'dash.smartClean': 'Smart clean in one click',
  'dash.cleaning': 'Smart cleaning…',
  'dash.scanDevice': 'Scan this machine',
  'dash.factors': 'Health factors',
  'dash.pinnedTools': 'Your pinned tools',
  'dash.quickTools': 'Quick tools',
  'dash.allTools': 'All tools',
  'dash.lastCleans': 'Recent cleans',
  'dash.cpu': 'CPU',
  'dash.memUsed': 'Memory in use',
  'dash.diskFree': 'Free space',
  'dash.uptime': 'Uptime',
  'dash.outOfTotal': 'of {size}',
  'dash.ofTotal': 'of {size}',
  'dash.hoursShort': '{n} hours',

  'health.evaluating': 'Checking your machine…',
  'health.excellent': 'Your machine is in great shape',
  'health.good': 'Your machine is in good shape',
  'health.fair': 'Your machine needs some care',
  'health.poor': 'Your machine needs a clean now',
  'health.canFree': 'About {size} can be freed in one click with no risk at all.',
  'health.clean': 'Nothing unnecessary worth cleaning right now.',
  'health.scanningDesc': 'Checking temporary files, memory, disk and startup programs…',
  'health.idleDesc': 'Press "Scan this machine" to check its current state.',
  'health.failed': 'Could not assess the machine: {msg}',
  'dash.cleanNothing': 'Nothing to clean — your machine is tidy',
  'dash.cleanDone': 'Freed {size} from {n} categories',
  'dash.cleanFailed': 'Smart clean failed: {msg}',

  // ---------- overview ----------
  'ov.measuring': 'Measuring your disk…',
  'ov.almostFull': 'Your disk is almost full',
  'ov.shrinking': 'Your free space is shrinking',
  'ov.healthy': 'Your disk space is healthy',
  'ov.freeSpace': 'Free space',
  'ov.perDay': 'Used per day',
  'ov.perDayDesc': 'How much space you use on an average day',
  'ov.needDays': 'We need a few days of measurements',
  'ov.forecast': 'Full-disk forecast',
  'ov.forecastDesc': 'Calculated from the last few days',
  'ov.forecastIn': 'At this rate the disk fills up in about {n} days',
  'ov.biggest': 'Biggest cleanup',
  'ov.highImpact': 'High impact',
  'ov.others': 'Other opportunities',
  'ov.planTasks': 'Plan tasks',
  'ov.allDone': 'Every plan task is done — your machine is in top shape',
  'ov.junkDetail': '{size} of temporary files and caches',
  'ov.dupDetail': 'Identical copies wasting space for nothing',
  'ov.largeDetail': 'The files eating the most space',
  'ov.dlDetail': 'What you forgot in Downloads months ago',

  // ---------- maintenance plan ----------
  'plan.never': 'Never done',
  'plan.today': 'Done today',
  'plan.daysAgo': 'Last done {n} days ago',
  'plan.every': 'every {n} days',
  'plan.markDone': 'Mark as done',
  'plan.marked': '"{label}" marked as done',
  'plan.badge.overdue': 'Overdue',
  'plan.badge.due': 'Due',
  'plan.badge.done': 'Done',
  'plan.task.junk': 'Clean unnecessary files',
  'plan.task.privacy': 'Clear browsing data',
  'plan.task.downloads': 'Tidy the Downloads folder',
  'plan.task.duplicates': 'Remove duplicate files',
  'plan.task.largefiles': 'Review the largest files',
  'plan.task.startup': 'Review startup programs',
  'plan.task.uninstaller': 'Uninstall programs you do not use',
  'plan.task.extras': 'Delete empty folders and broken shortcuts',

  // ---------- settings ----------
  'set.language': 'Language',
  'set.language.sub': 'The interface direction switches automatically',
  'set.arabic': 'العربية',
  'set.english': 'English',
  'set.appearance': 'Appearance',
  'set.theme': 'Theme',
  'set.accent': 'Accent colour',
  'set.accent.sub': 'Buttons and active elements',
  'set.behavior': 'Behaviour',
  'set.tray': 'Minimise to the system tray',
  'set.tray.sub': 'The app keeps running when you close the window',
  'set.launch': 'Launch at login',
  'set.launch.sub': 'Opens automatically after you sign in',
  'set.notif': 'Notify when cleaning finishes',
  'set.notif.sub': 'Shows how much space was freed',
  'set.autoscan': 'Scan automatically on launch',
  'set.autoscan.sub': 'Computes the health score as soon as the app opens',
  'set.tools': 'Tools',
  'set.dlAge': 'Old download age',
  'set.shredPasses': 'Shredder passes',
  'set.once': 'Once',
  'set.times': '{n} times',
  'set.daysN': '{n} days',
  'set.about': 'About',
  'set.saveFailed': 'Could not save the setting: {msg}',
  'set.shortcuts': 'Keyboard shortcuts',
  'set.sc.palette': 'Command palette',
  'set.sc.settings': 'Settings',
  'set.sc.theme': 'Switch theme',

  // ---------- shared components ----------
  'palette.empty': 'No results for "{q}"',
  'palette.kMove': 'move',
  'palette.kOpen': 'open',
  'palette.kClose': 'close',
  'batch.title': 'Batch rename ({n} files)',
  'batch.hint': 'Use %name% for the original name, %n% for a counter, %ext% for the extension',
  'batch.start': 'Start number',
  'batch.applying': 'Applying…',
  'batch.done': 'Renamed {n} files',
  'batch.partial': 'Renamed {n} files, {fail} failed ({msg})',
  'batch.failed': 'Some operations failed: {msg}',
  'scan.hashing': 'Comparing file contents… {i} of {n}',
  'scan.walking': 'Scanning folders… {n} files',

  // ---------- settings (detail) ----------
  'set.appearance.sub': 'Pick what is easy on your eyes — saved automatically',
  'set.theme.sub': '"System" follows your {os} setting automatically',
  'set.accent.sub2': 'Recolours the cards and buttons across the whole app',
  'set.behavior.sub': 'How the app behaves in the background',
  'set.tray.sub2': 'Closing the window hides it instead of quitting, and smart clean stays available from the icon',
  'set.launch.sub2': 'CleanShelf starts hidden with the system (installed build only)',
  'set.notif.sub2': 'Tells you how much space a finished clean freed',
  'set.autoscan.sub2': 'Computes the health score automatically — turn it off if scanning is slow on your machine',
  'set.tools.sub': 'Default settings for the tools',
  'set.dlAge.sub': 'Files older than this many days show up in the Old downloads tool',
  'set.shred.sub': 'More passes = slower and harder to recover; 3 is enough for most uses',
  'set.shred.1': 'Once (fast)',
  'set.shred.3': '3 times (recommended)',
  'set.shred.7': '7 times (maximum)',
  'set.forWinMac': 'for Windows and macOS',
  'set.checkUpdate': 'Check for a newer release',
  'os.windows': 'Windows',
  'os.mac': 'macOS',

  // ---------- cleaner categories ----------
  'cleaner.userTemp.t': 'User temporary files',
  'cleaner.userTemp.d': 'Temporary files programs leave behind while running',
  'cleaner.windowsTemp.t': 'Windows temporary files',
  'cleaner.windowsTemp.d': 'Windows\' own Temp folder',
  'cleaner.prefetch.t': 'Prefetch cache',
  'cleaner.prefetch.d': 'Windows rebuilds it automatically; usually safe but a program may start slower once',
  'cleaner.windowsUpdate.t': 'Windows Update downloads',
  'cleaner.windowsUpdate.d': 'Copies of updates that are already installed',
  'cleaner.thumbnails.t': 'Thumbnail cache',
  'cleaner.thumbnails.d': 'Windows recreates it when needed',
  'cleaner.errorReports.t': 'Windows error reports',
  'cleaner.errorReports.d': 'Old crash diagnostics',
  'cleaner.recentList.t': 'Recent files list',
  'cleaner.recentList.d': 'Shortcuts to the files you opened last',
  'cleaner.chromeCache.t': 'Chrome cache',
  'cleaner.chromeCache.d': 'Rebuilt automatically as you browse',
  'cleaner.edgeCache.t': 'Edge cache',
  'cleaner.edgeCache.d': 'Rebuilt automatically as you browse',
  'cleaner.firefoxCache.t': 'Firefox cache',
  'cleaner.firefoxCache.d': 'Rebuilt automatically as you browse',
  'cleaner.deliveryOptimization.t': 'Delivery Optimization files',
  'cleaner.deliveryOptimization.d': 'Update chunks shared with other machines on your network',
  'cleaner.minidumps.t': 'Memory dumps (Minidump)',
  'cleaner.minidumps.d': 'System crash diagnostics',
  'cleaner.recycleBin.t': 'Recycle Bin',
  'cleaner.recycleBin.d': 'Empties the Recycle Bin permanently — cannot be undone',
  'cleaner.mac.userCaches.t': 'User caches',
  'cleaner.mac.userCaches.d': '~/Library/Caches — rebuilt automatically',
  'cleaner.mac.systemCaches.t': 'System caches',
  'cleaner.mac.systemCaches.d': '/Library/Caches — needs elevated permissions',
  'cleaner.mac.userLogs.t': 'Application logs',
  'cleaner.mac.userLogs.d': '~/Library/Logs',
  'cleaner.mac.trash.t': 'Trash',
  'cleaner.mac.trash.d': 'Empties the Trash permanently — cannot be undone',
  'cleaner.mac.xcodeDerived.t': 'Xcode derived data',
  'cleaner.mac.xcodeDerived.d': 'DerivedData — rebuilt when you open the project, often several GB',
  'cleaner.mac.xcodeDeviceSupport.t': 'Xcode device support',
  'cleaner.mac.xcodeDeviceSupport.d': 'Symbol copies for old iOS versions — re-downloaded when needed',
  'cleaner.mac.xcodeArchives.t': 'Xcode archives',
  'cleaner.mac.xcodeArchives.d': 'Archived builds for distribution — delete what you no longer need',
  'cleaner.mac.homebrew.t': 'Homebrew cache',
  'cleaner.mac.homebrew.d': 'Packages downloaded earlier',
  'cleaner.mac.packageManagers.t': 'Package manager caches',
  'cleaner.mac.packageManagers.d': 'npm, Yarn, pnpm, pip, Gradle and CocoaPods',
  'cleaner.mac.safariCache.t': 'Safari cache',
  'cleaner.mac.safariCache.d': 'Rebuilt as you browse',
  'cleaner.mac.mailDownloads.t': 'Mail attachment cache',
  'cleaner.mac.mailDownloads.d': 'Attachments opened from the Mail app',
  'cleaner.mac.iosBackups.t': 'iPhone/iPad backups',
  'cleaner.mac.iosBackups.d': 'Can be tens of GB — make sure you have another copy first',
  'cleaner.mac.crashReports.t': 'Crash reports',
  'cleaner.mac.crashReports.d': 'Application crash diagnostics',
  'cleaner.mac.quicklook.t': 'Quick Look cache',
  'cleaner.mac.quicklook.d': 'Thumbnails the system rebuilds',
  'cleaner.mac.savedState.t': 'Saved application state',
  'cleaner.mac.savedState.d': 'Previously open windows are lost on restart',

  // ---------- disk cleaner ----------
  'cl.scanFailed': 'Scan failed: {msg}',
  'cl.restorePoint': 'Creating a restore point… this can take a minute',
  'cl.restoreFailed': 'Could not create the restore point: {msg}',
  'cl.freed': 'Freed {size} of space',
  'cl.cleanError': 'Something went wrong while cleaning: {msg}',
  'cl.summary': '{n} categories, {size} cleanable in total',
  'cl.selectedLabel': 'Selected:',
  'cl.cleanSelected': 'Clean selected',
  'cl.cleaning': 'Cleaning…',
  'cl.adminTitle': 'Some categories need elevated permissions',
  'cl.adminBody': 'These categories live in system-owned folders and nothing will be deleted from them with your current permissions:',
  'cl.adminMac': ' macOS has no "relaunch as administrator"; clean them from the terminal or skip these categories.',
  'cl.relaunchAdmin': 'Relaunch as administrator',
  'cl.thCategory': 'Category',
  'cl.thFiles': 'Files',
  'cl.caution': 'Caution',
  'cl.adminBadge': 'Admin',
  'cl.adminBadgeTip': 'Requires running the app as administrator',
  'cl.failed': 'Failed',
  'cl.freedBadge': 'Freed {size}',
  'cl.working': 'Working…',
  'cl.error': 'Error',
  'cl.ready': 'Ready',
  'cl.confirmTitle': 'Confirm cleaning',
  'cl.confirmBody': '{size} from {n} categories will be deleted permanently (including the Recycle Bin, which is emptied for good).',
  'cl.confirmCaution': 'You picked categories marked "Caution" — make sure you understand what they do before continuing.',
  'cl.makeRestore': 'Create a system restore point first (needs administrator rights, may take a minute)',

  // ---------- pages: history, duplicates, large files, system ----------
  'hi.clearConfirm': 'Clear the whole cleaning history?',
  'hi.cleared': 'History cleared',
  'hi.totalFreed': 'Total freed',
  'hi.ops': 'Cleaning runs',
  'hi.lastClean': 'Last clean',
  'hi.sub': 'A log of your previous cleans',
  'hi.clear': 'Clear history',
  'hi.none': 'No cleaning has run yet',
  'hi.thFreed': 'Space freed',
  'hi.thCats': 'Categories',
  'du.none': 'No duplicate files found',
  'du.stopped': 'Scan stopped',
  'du.failed': 'Search failed: {msg}',
  'du.trashConfirm': 'Move {n} files to the Recycle Bin?',
  'du.trashDetail': 'At least one copy from every duplicate group is kept unless you choose otherwise.',
  'du.deleted': 'Deleted {n} files',
  'du.pick': 'Pick a folder and search for duplicates',
  'du.wasted': 'Estimated waste: {size}',
  'du.selectExtra': 'Select all but the first in each group',
  'du.deleteSel': 'Delete selected ({n})',
  'du.empty': 'Pick a folder to start looking for duplicates',
  'du.copies': '{n} copies × {size}',
  'lf.pick': 'Pick a folder',
  'lf.biggerThan': 'Bigger than {size}',
  'lf.empty': 'Pick a folder to list its largest files',
  'lf.thFile': 'File',
  'lf.reveal': 'Reveal',
  'lf.trashConfirm': 'Move {n} files to the Recycle Bin?',
  'si.failed': 'Could not read system info: {msg}',
  'si.system': 'System',
  'si.host': 'Machine',
  'si.os': 'Operating system',
  'si.version': 'Version',
  'si.cpuMem': 'CPU & memory',
  'si.usage': 'Load',
  'si.totalMem': 'Total memory',
  'si.disks': 'Disks',
  'si.thDisk': 'Disk',
  'si.thUsed': 'Used',
  'si.thFree': 'Free',

  // ---------- pages: analyzer, extras, report, startup ----------
  'da.stopped': 'Analysis stopped',
  'da.failed': 'Analysis failed: {msg}',
  'da.trashConfirm': 'Move "{name}" to the Recycle Bin?',
  'da.trashDetail': '{path}\\nSize: {size}',
  'da.moved': 'Moved to the Recycle Bin',
  'da.deleteFailed': 'Delete failed: {msg}',
  'da.pick': 'Pick a folder or a drive',
  'da.up': 'Up',
  'da.total': 'Total: {size}',
  'da.empty': 'Pick a folder to see exactly where your space goes',
  'da.emptyFolder': 'This folder is empty',
  'da.thItem': 'Item',
  'da.thShare': 'Share',
  'da.thFiles': 'Files',
  'da.openIt': 'Open',
  'ex.noEmpty': 'No empty folders found',
  'ex.noBroken': 'No broken shortcuts found',
  'ex.scanFailed': 'Scan failed: {msg}',
  'ex.trashConfirm': 'Move {n} items to the Recycle Bin?',
  'ex.trashDetail': 'You can restore them from the Recycle Bin if you change your mind.',
  'ex.deleted': 'Deleted {n} items',
  'ex.modeEmpty': 'Empty folders',
  'ex.modeShortcuts': 'Broken shortcuts',
  'ex.pick': 'Pick a folder and scan',
  'ex.deleteSel': 'Delete selected ({n})',
  'ex.emptyHint': 'Pick a folder to look for completely empty folders',
  'ex.shortcutsHint': 'Pick a folder to look for shortcuts whose target is gone',
  'ex.thFolder': 'Folder',
  'ex.thShortcut': 'Shortcut',
  'ex.thTarget': 'Missing target',
  'rp.failed': 'Could not build the report: {msg}',
  'rp.saved': 'Report saved',
  'rp.copied': 'Report copied',
  'rp.copyFailed': 'Could not copy',
  'rp.building': 'Gathering information…',
  'rp.rebuild': 'Rebuild report',
  'rp.build': 'Build report',
  'rp.generatedAt': 'Generated {date}',
  'rp.saveFile': 'Save as a file',
  'rp.hint': 'The report gathers system info, disks, what can be cleaned, startup programs and installed software into one Markdown file — handy for support, or as a snapshot before a big change.',
  'rp.empty': 'Press "Build report" for a full snapshot of your machine',
  'su.HKCU-Run': 'Current user (Run)',
  'su.HKLM-Run': 'All users (Run)',
  'su.StartupFolder-User': 'Startup folder (user)',
  'su.StartupFolder-Common': 'Startup folder (shared)',
  'su.loadFailed': 'Could not read startup programs: {msg}',
  'su.opFailed': 'The operation failed: {msg}',
  'su.deleteConfirm': 'Remove "{name}" from startup permanently?',
  'su.deleteFailed': 'Delete failed: {msg}',
  'su.count': '{n} items',
  'su.thCommand': 'Command / path',
  'su.thLocation': 'Location',
  'su.enabled': 'Enabled',
  'su.disabled': 'Disabled',
  'su.disable': 'Disable',
  'su.enable': 'Enable',

  // ---------- pages: processes, services, network, privacy ----------
  'pr.failed': 'Could not read processes: {msg}',
  'pr.killConfirm': 'End the process "{name}"?',
  'pr.killDetail': 'You may lose unsaved work in that program. Do not end system processes unless you are sure.',
  'pr.searchPh': 'Search by process name…',
  'pr.sortMem': 'Sort by memory',
  'pr.sortCpu': 'Sort by CPU',
  'pr.sortName': 'Sort by name',
  'pr.autoRefresh': 'Auto refresh',
  'pr.count': '{n} processes — {size}',
  'pr.thPid': 'PID',
  'pr.thMem': 'Memory',
  'pr.thUser': 'User',
  'pr.kill': 'End task',
  'sv.running': 'Running',
  'sv.stopped': 'Stopped',
  'sv.paused': 'Paused',
  'sv.unknown': 'Unknown',
  'sv.boot': 'At boot',
  'sv.system': 'System',
  'sv.automatic': 'Automatic',
  'sv.manual': 'Manual',
  'sv.disabled': 'Disabled',
  'sv.failed': 'Could not read services: {msg}',
  'sv.stopConfirm': 'Stop the service "{name}"?',
  'sv.stopDetail': 'Stopping system services can break Windows features until they are started again.',
  'sv.searchPh': 'Search by service name…',
  'sv.runningOnly': 'Running only',
  'sv.count': '{n} services',
  'sv.warn': 'Starting and stopping services needs elevated permissions. Services are part of how the system works internally (Windows services or launchd jobs on macOS), so do not stop one whose job you do not know.',
  'sv.thService': 'Service',
  'sv.thStartType': 'Start type',
  'sv.stop': 'Stop',
  'sv.restart': 'Restart',
  'sv.start': 'Start',
  'nw.failed': 'Could not read network info: {msg}',
  'nw.count': '{a} adapters, {c} active connections',
  'nw.flushDns': 'Flush DNS cache',
  'nw.pingTitle': 'Connection test',
  'nw.pingPh': 'e.g. google.com',
  'nw.pinging': 'Testing…',
  'nw.ping': 'Test',
  'nw.pingAvg': 'Average response {ms} ms',
  'nw.adapters': 'Network adapters',
  'nw.thAdapter': 'Adapter',
  'nw.thIp': 'IP address',
  'nw.thSpeed': 'Speed',
  'nw.thTraffic': 'Down / up',
  'nw.up': 'Connected',
  'nw.down': 'Disconnected',
  'nw.connections': 'Active connections',
  'nw.thApp': 'Program',
  'nw.thProto': 'Protocol',
  'nw.thLocal': 'Local',
  'nw.thRemote': 'Remote',
  'pv.history.t': 'Browsing history',
  'pv.history.d': 'Sites you visited and their stored icons',
  'pv.cookies.t': 'Cookies',
  'pv.cookies.d': 'You will be signed out of every site',
  'pv.sessions.t': 'Saved sessions',
  'pv.sessions.d': 'Tabs the browser restores when it opens',
  'pv.formdata.t': 'Form data',
  'pv.formdata.d': 'Autofill for addresses and searches',
  'pv.scanFailed': 'Scan failed: {msg}',
  'pv.clearConfirm': 'Clear {n} items of browser data?',
  'pv.cookieWarn': 'You will need to sign in to sites again. ',
  'pv.closeFirst': 'Close your browsers first, otherwise files in use cannot be deleted.',
  'pv.cleared': 'Cleared {n} items and freed {size}',
  'pv.partial': '{fail} of {n} failed: {msg}',
  'pv.searching': 'Looking for browsers…',
  'pv.count': '{b} browsers, {n} items',
  'pv.clearing': 'Clearing…',
  'pv.clearSel': 'Clear selected ({size})',
  'pv.note': 'Close the browser before clearing — its files are locked while it runs. Bookmarks and saved passwords are never touched. Firefox history is not listed because it lives in the same file as your bookmarks.',
  'pv.none': 'No browser data found on this machine'
}
