/** The English dictionary — mirrors dict.ar.ts key for key. */
export const EN: Record<string, string> = {
  // ---------- common ----------
  'app.name': 'CleanShelf',
  'app.by': 'by Alcode',
  'app.byShort': 'by {company}',

  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.save': 'Save',
  'common.saving': 'Saving…',
  'common.delete': 'Delete',
  'common.remove': 'Remove',
  'common.close': 'Close',
  'common.apply': 'Apply',
  'common.open': 'Open',
  'common.refresh': 'Refresh',
  'common.rescan': 'Scan again',
  'common.scan': 'Scan',
  'common.scanning': 'Scanning…',
  'common.stopScan': 'Stop scan',
  'common.loading': 'Loading…',
  'common.search': 'Search',
  'common.searchQuick': 'Quick search…',
  'common.selectAll': 'Select all',
  'common.clearAll': 'Clear selection',
  'common.selected': 'Selected',
  'common.viewAll': 'View all',
  'common.viewDetails': 'View details',
  'common.details': 'Details',
  'common.name': 'Name',
  'common.size': 'Size',
  'common.date': 'Date',
  'common.path': 'Path',
  'common.status': 'Status',
  'common.type': 'Type',
  'common.free': 'free',
  'common.used': 'used',
  'common.total': 'Total',
  'common.item': 'item',
  'common.items': 'items',
  'common.file': 'file',
  'common.files': 'files',
  'common.day': 'day',
  'common.days': 'days',
  'common.hours': 'hours',
  'common.category': 'category',
  'common.categories': 'categories',
  'common.nothing': 'Nothing',
  'common.empty': 'Nothing here',
  'common.failed': 'Something went wrong',
  'common.settings': 'Settings',
  'common.back': 'Back',
  'common.retry': 'Try again',
  'common.copy': 'Copy',
  'common.copied': 'Copied',

  'unit.b': 'B',
  'unit.kb': 'KB',
  'unit.mb': 'MB',
  'unit.gb': 'GB',
  'unit.tb': 'TB',

  // ---------- sidebar and page titles ----------
  'nav.disk': 'Disk tools',
  'nav.privacy': 'Privacy & security',
  'nav.system': 'System',
  'nav.pin': 'Pin to the dashboard',
  'nav.unpin': 'Unpin',

  'page.dashboard': 'Dashboard',
  'page.dashboard.sub': 'Your machine at a glance, and a one-click clean',
  'page.overview': 'Overview',
  'page.overview.sub': 'Disk forecast and your biggest cleanup wins',
  'page.plan': 'Maintenance plan',
  'page.plan.sub': 'Recurring tasks that keep your machine tidy',
  'page.cleaner': 'Disk cleaner',
  'page.cleaner.sub': 'Free up space by deleting what you do not need',
  'page.uninstaller': 'Uninstall programs',
  'page.uninstaller.sub': 'Remove installed programs along with their leftovers',
  'page.files': 'File manager',
  'page.files.sub': 'Browse, rename and organise your files',
  'page.tags': 'Music tag editor',
  'page.tags.sub': 'Edit MP3 tags and cover art, Mp3tag style',
  'page.duplicates': 'Duplicate files',
  'page.duplicates.sub': 'Find identical copies and win the space back',
  'page.largefiles': 'Largest files',
  'page.largefiles.sub': 'Spot the files eating the most space',
  'page.startup': 'Startup programs',
  'page.startup.sub': 'Control what runs automatically at boot',
  'page.system': 'System info',
  'page.system.sub': 'CPU, memory and disk status',
  'page.processes': 'Processes',
  'page.processes.sub': 'What is running right now, and how to end it',
  'page.services': 'System services',
  'page.services.sub': 'Start and stop Windows services and launchd jobs',
  'page.network': 'Network',
  'page.network.sub': 'Adapters, live connections and diagnostics',
  'page.diskanalyzer': 'Space analyser',
  'page.diskanalyzer.sub': 'See exactly where your disk space goes',
  'page.extras': 'Folders & shortcuts',
  'page.extras.sub': 'Empty folders and broken shortcuts',
  'page.history': 'Cleaning history',
  'page.history.sub': 'What was cleaned before and how much it freed',
  'page.mactools': 'Mac tools',
  'page.mactools.sub': 'Leftovers of deleted apps and language files',
  'page.privacy': 'Browser privacy',
  'page.privacy.sub': 'Clear history, cookies and sessions from every browser',
  'page.shredder': 'Secure shredder',
  'page.shredder.sub': 'Destroy sensitive files beyond recovery',
  'page.downloads': 'Old downloads',
  'page.downloads.sub': 'What you forgot in Downloads months ago',
  'page.report': 'System report',
  'page.report.sub': 'A full snapshot of your machine you can save or share',
  'page.settings': 'Settings',
  'page.settings.sub': 'Appearance, language, behaviour and tool options',

  // ---------- command palette ----------
  'palette.pages': 'Pages',
  'palette.actions': 'Actions',
  'palette.placeholder': 'Type a page or an action…',
  'palette.noResults': 'No results',
  'palette.smartClean': 'Smart clean now',
  'palette.theme': 'Switch theme (currently: {mode})',
  'palette.lang': 'Switch language (currently: {lang})',
  'palette.report': 'Build a system report',
  'palette.hintOpen': 'to open',
  'palette.hintMove': 'to move',

  // ---------- appearance ----------
  'theme.system': 'System',
  'theme.light': 'Light',
  'theme.dark': 'Dark',
  'theme.tip': 'Theme: {mode} — click to switch',

  // ---------- dashboard ----------
  'dash.period.week': 'This week',
  'dash.period.month': 'This month',
  'dash.period.year': 'This year',
  'dash.mainDisk': 'Main disk',
  'dash.planTile': 'Maintenance plan',
  'dash.diskTile': 'Disk status',
  'dash.overdue': 'Overdue',
  'dash.due': 'Due now',
  'dash.inPlan': 'In plan',
  'dash.done': 'Completed',
  'dash.seg.used': 'Used',
  'dash.seg.junk': 'Cleanable',
  'dash.seg.free': 'Free',
  'dash.totalOf': '{unit} total',
  'dash.outOf100': 'out of 100',
  'dash.smartClean': 'Smart clean in one click',
  'dash.cleaning': 'Smart cleaning…',
  'dash.scanDevice': 'Scan this machine',
  'dash.factors': 'Health factors',
  'dash.pinnedTools': 'Your pinned tools',
  'dash.quickTools': 'Quick tools',
  'dash.allTools': 'All tools',
  'dash.lastCleans': 'Recent cleans',
  'dash.cpu': 'CPU',
  'dash.memUsed': 'Memory in use',
  'dash.diskFree': 'Free space',
  'dash.uptime': 'Uptime',
  'dash.outOfTotal': 'of {size}',
  'dash.ofTotal': 'of {size}',
  'dash.hoursShort': '{n} hours',

  'health.evaluating': 'Checking your machine…',
  'health.excellent': 'Your machine is in great shape',
  'health.good': 'Your machine is in good shape',
  'health.fair': 'Your machine needs some care',
  'health.poor': 'Your machine needs a clean now',
  'health.canFree': 'About {size} can be freed in one click with no risk at all.',
  'health.clean': 'Nothing unnecessary worth cleaning right now.',
  'health.scanningDesc': 'Checking temporary files, memory, disk and startup programs…',
  'health.idleDesc': 'Press "Scan this machine" to check its current state.',
  'health.failed': 'Could not assess the machine: {msg}',
  'dash.cleanNothing': 'Nothing to clean — your machine is tidy',
  'dash.cleanDone': 'Freed {size} from {n} categories',
  'dash.cleanFailed': 'Smart clean failed: {msg}',

  // ---------- overview ----------
  'ov.measuring': 'Measuring your disk…',
  'ov.almostFull': 'Your disk is almost full',
  'ov.shrinking': 'Your free space is shrinking',
  'ov.healthy': 'Your disk space is healthy',
  'ov.freeSpace': 'Free space',
  'ov.perDay': 'Used per day',
  'ov.perDayDesc': 'How much space you use on an average day',
  'ov.needDays': 'We need a few days of measurements',
  'ov.forecast': 'Full-disk forecast',
  'ov.forecastDesc': 'Calculated from the last few days',
  'ov.forecastIn': 'At this rate the disk fills up in about {n} days',
  'ov.biggest': 'Biggest cleanup',
  'ov.highImpact': 'High impact',
  'ov.others': 'Other opportunities',
  'ov.planTasks': 'Plan tasks',
  'ov.allDone': 'Every plan task is done — your machine is in top shape',
  'ov.junkDetail': '{size} of temporary files and caches',
  'ov.dupDetail': 'Identical copies wasting space for nothing',
  'ov.largeDetail': 'The files eating the most space',
  'ov.dlDetail': 'What you forgot in Downloads months ago',

  // ---------- maintenance plan ----------
  'plan.never': 'Never done',
  'plan.today': 'Done today',
  'plan.daysAgo': 'Last done {n} days ago',
  'plan.every': 'every {n} days',
  'plan.markDone': 'Mark as done',
  'plan.marked': '"{label}" marked as done',
  'plan.badge.overdue': 'Overdue',
  'plan.badge.due': 'Due',
  'plan.badge.done': 'Done',
  'plan.task.junk': 'Clean unnecessary files',
  'plan.task.privacy': 'Clear browsing data',
  'plan.task.downloads': 'Tidy the Downloads folder',
  'plan.task.duplicates': 'Remove duplicate files',
  'plan.task.largefiles': 'Review the largest files',
  'plan.task.startup': 'Review startup programs',
  'plan.task.uninstaller': 'Uninstall programs you do not use',
  'plan.task.extras': 'Delete empty folders and broken shortcuts',

  // ---------- settings ----------
  'set.language': 'Language',
  'set.language.sub': 'The interface direction switches automatically',
  'set.arabic': 'العربية',
  'set.english': 'English',
  'set.appearance': 'Appearance',
  'set.theme': 'Theme',
  'set.accent': 'Accent colour',
  'set.accent.sub': 'Buttons and active elements',
  'set.behavior': 'Behaviour',
  'set.tray': 'Minimise to the system tray',
  'set.tray.sub': 'The app keeps running when you close the window',
  'set.launch': 'Launch at login',
  'set.launch.sub': 'Opens automatically after you sign in',
  'set.notif': 'Notify when cleaning finishes',
  'set.notif.sub': 'Shows how much space was freed',
  'set.autoscan': 'Scan automatically on launch',
  'set.autoscan.sub': 'Computes the health score as soon as the app opens',
  'set.tools': 'Tools',
  'set.dlAge': 'Old download age',
  'set.shredPasses': 'Shredder passes',
  'set.once': 'Once',
  'set.times': '{n} times',
  'set.daysN': '{n} days',
  'set.about': 'About',
  'set.saveFailed': 'Could not save the setting: {msg}',
  'set.shortcuts': 'Keyboard shortcuts',
  'set.sc.palette': 'Command palette',
  'set.sc.settings': 'Settings',
  'set.sc.theme': 'Switch theme',

  // ---------- shared components ----------
  'palette.empty': 'No results for "{q}"',
  'palette.kMove': 'move',
  'palette.kOpen': 'open',
  'palette.kClose': 'close',
  'batch.title': 'Batch rename ({n} files)',
  'batch.hint': 'Use %name% for the original name, %n% for a counter, %ext% for the extension',
  'batch.start': 'Start number',
  'batch.applying': 'Applying…',
  'batch.done': 'Renamed {n} files',
  'batch.partial': 'Renamed {n} files, {fail} failed ({msg})',
  'batch.failed': 'Some operations failed: {msg}',
  'scan.hashing': 'Comparing file contents… {i} of {n}',
  'scan.walking': 'Scanning folders… {n} files',

  // ---------- settings (detail) ----------
  'set.appearance.sub': 'Pick what is easy on your eyes — saved automatically',
  'set.theme.sub': '"System" follows your {os} setting automatically',
  'set.accent.sub2': 'Recolours the cards and buttons across the whole app',
  'set.behavior.sub': 'How the app behaves in the background',
  'set.tray.sub2': 'Closing the window hides it instead of quitting, and smart clean stays available from the icon',
  'set.launch.sub2': 'CleanShelf starts hidden with the system (installed build only)',
  'set.notif.sub2': 'Tells you how much space a finished clean freed',
  'set.autoscan.sub2': 'Computes the health score automatically — turn it off if scanning is slow on your machine',
  'set.tools.sub': 'Default settings for the tools',
  'set.dlAge.sub': 'Files older than this many days show up in the Old downloads tool',
  'set.shred.sub': 'More passes = slower and harder to recover; 3 is enough for most uses',
  'set.shred.1': 'Once (fast)',
  'set.shred.3': '3 times (recommended)',
  'set.shred.7': '7 times (maximum)',
  'set.forWinMac': 'for Windows and macOS',
  'set.checkUpdate': 'Check for a newer release',
  'os.windows': 'Windows',
  'os.mac': 'macOS'
}
